### ISSUE TITLE
[V2] Error: Couldn't find the binary git

### ISSUE THREAD

**Issue by brunolemos** [vercel/vercel#1661] opened 2018-11-15 08:02 UTC
When there is a package that uses a version from github instead of npm, the deploy fails:
`Error: Couldn't find the binary git`

Related but closed: https://github.com/zeit/now-cli/issues/1013

**Comment by leo** [comment] 2018-11-15 17:54
@brunolemos Are you sure you are using `version: 2`?

**Comment by brunolemos** [comment] 2018-11-15 18:41
@leo yeah. 

I was not able to isolate the issue. If I just use a github url on my package.json and ignore everything else it works. So Now seems to understand git urls.

This error seems to be coming from some package that I don't know which.
Maybe some package is trying to use the git binary?

Logs: https://zeit.co/brunolemos/devhub/8pf9y0a7f/logs _[deleted]_

---

_PS: I also opened #1666, it's related to git but might be a different issue. I removed `patch-package` completely from my project and kept getting `Couldn't find the binary git`._

**Comment by leo** [comment] 2018-11-15 19:13
@brunolemos It appears that some other code in your deployment is trying to invoke `git` (even after `patch-package` is removed).

But just to be clear: You need `git` while your deployment is built, right? Not in runtime.

**Comment by brunolemos** [comment] 2018-11-15 19:18
Yes. My project doesn't need `git`. `patch-package` uses it once after yarn install. 

I don't know if there's any dependency using the binary, nor why would they, I'll try to find out. 

If it turns out to be the case,
@leo Does Now plan to add the git binary?

**Comment by brunolemos** [comment] 2018-11-15 20:06
Ok I investigated more...

I don't know why but now the deploy is working after I removed patch-package again. 

I didn't have to remove the dependency, only the `"prepare": "patch-package"` script. If re-add this script I get #1666 or #1664.

I enjoy using this dependency so I don't have to make forks, so I just need to know if Now plans to have a git binary available on deployments so patch-package can work.

**Comment by TooTallNate** [comment] 2018-11-15 20:18
We are indeed adding the `git` binary to the build environment.

**Comment by robcrocombe** [comment] 2018-11-20 09:15
Any update on adding the `git` binary yet? It's the last piece of the puzzle for one of my projects (getting it to work on Now).

In the other thread @brunolemos mentioned "Now V2 supports git urls for dependencies" but I still can't get it to work? I've tried all these:

```
"dependency": "username/repo"
"dependency": "git@github.com:username/repo.git"
"dependency": "git+https://github.com/username/repo.git"
```

Am I doing something wrong there? (Using npm 5.5.1 and node 9.3.0 locally)

**Comment by robcrocombe** [comment] 2018-11-20 14:47
Like this? `"dependency": "https://github.com/username/repo"` It resolves to the `git+https` version in my `package-lock.json` and I still get the error in Now, unfortunately.

**Comment by maxmx** [comment] 2018-11-21 22:52
Got the same problem. Not doing anything fancy just deploying a gatsby static site using v2 and now static-builder

https://zeit.co/maxmx/mobilo/n3e8q3vky/logs

**Comment by TooTallNate** [comment] 2018-11-21 22:58
Closing since this is a duplicate of https://github.com/zeit/now-builders/issues/49 (and that's the repo where the fix will actually take place).

**Closed as completed by TooTallNate** 2018-11-21 22:58 UTC
