### ISSUE TITLE
deployment name length over 63chars throws incorrect error

### ISSUE THREAD

**Issue by StanLindsey** [vercel/vercel#1812] opened 2019-01-08 17:06 UTC
If you attempt to create a deployment with a length greater than the 63 chars that DNS allows, it will fail. This obviously makes sense. 

`now` throws errors relating to a missing `now.json`, even if it does exist.
I suggest the CLI checks if the length is over the limit, and either substrings it or throws a relevant error.

```
> WARN! Your project is missing a now.json file with a `version` property. More: https://zeit.co/docs/version-config
> Deploying /dist
> Error! Failed to validate now.json. Only use properties mentioned here: https://zeit.co/docs/v2/deployments/configuration/

{ Error: Command failed: now ./dist --name="test-this-is-a-really-long-name-test-this-is-a-really-long-name-test-this-is-a-really-long-name-test" 
> WARN! Your project is missing a now.json file with a `version` property. More: https://zeit.co/docs/version-config
> Deploying /dist
> Error! Failed to validate now.json. Only use properties mentioned here: https://zeit.co/docs/v2/deployments/configuration/

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'now ./dist --name="test-this-is-a-really-long-name-test-this-is-a-really-long-name-test-this-is-a-really-long-name-test"' }
ERROR: Job failed: exit code 1
```

**Comment by timothyis** [comment] 2019-01-08 17:19
Could you share the `now.json` file here? I don't think the error is that you don't have a `now.json` file but that you don't have the `version` property inside of it, which Now requires: https://zeit.co/docs/v2/deployments/configuration/#version

**Comment by StanLindsey** [comment] 2019-01-09 08:59
The issue disappears after trimming my deployment name to 52 chars (53 chars fails and throws the above error). I get the same fail and success results whether I have a `now.json` or not. 

Adding `now.json` didn't fix the problem, but trimming the string length did.
My current now.json is simply: 
```
{
  version: 2
}
```

**Comment by timothyis** [comment] 2019-01-09 15:35
@StanLindsey that isn't valid JSON, however. Try this:
```json
{
  "version": 2
}
```

**Comment by michaellopez** [comment] 2019-01-25 04:19
Wow, this was a bug that was hard to track down. Thanks @StanLindsey for finally giving me some faith in my sanity. I was close to going mad on this one. Hopefully my "me too/+1" can give you peace of mind that you are not alone on this one (albeit two weeks too late)

We are also hitting this. We generate a unique deployment name through our CI which is basically `${prefix}-${project}-${branch}` and some deployments fail and some don't. I couldn't figure out why. We also do not include any `now.json` file at all, as we deploy Next.js statically exported sites only, we pass version flag in the CLI command and it works great until we generate a deployment name greater than 52 characters.

@timothyis Based on our setup, I can confirm that everything else is in order as it should be. Only thing that differs is the deployment name, going over 52 chars gives the dreaded error `Error! Failed to validate now.json. Only use properties mentioned here: https://zeit.co/docs/v2/deployments/configuration/`.

See for yourself:

```sh
# 55 chars
$ now -V 2 -T weahead -t <token> ./out -n 1234567890123456789012345678901234567890123456789012345
> WARN! Your project is missing a now.json file with a `version` property. More: https://zeit.co/docs/version-config
> Deploying ~/out under weahead
> Using project 1234567890123456789012345678901234567890123456789012345
> Error! Failed to validate now.json. Only use properties mentioned here: https://zeit.co/docs/v2/deployments/configuration/

# 54 chars
$ now -V 2 -T weahead -t <token> ./out -n 123456789012345678901234567890123456789012345678901234
> WARN! Your project is missing a now.json file with a `version` property. More: https://zeit.co/docs/version-config
> Deploying ~/out under weahead
> Using project 123456789012345678901234567890123456789012345678901234
> Error! Failed to validate now.json. Only use properties mentioned here: https://zeit.co/docs/v2/deployments/configuration/

# 53 chars
$ now -V 2 -T weahead -t <token> ./out -n 12345678901234567890123456789012345678901234567890123
> WARN! Your project is missing a now.json file with a `version` property. More: https://zeit.co/docs/version-config
> Deploying ~/out under weahead
> Using project 12345678901234567890123456789012345678901234567890123
> Error! Failed to validate now.json. Only use properties mentioned here: https://zeit.co/docs/v2/deployments/configuration/

# 52 chars
$ now -V 2 -T weahead -t <token> ./out -n 1234567890123456789012345678901234567890123456789012
> WARN! Your project is missing a now.json file with a `version` property. More: https://zeit.co/docs/version-config
> Deploying ~/out under weahead
> Using project 1234567890123456789012345678901234567890123456789012
> https://1234567890123456789012345678901234567890123456789012-<hash>.now.sh [v2] [in clipboard] [3s]
┌ **        Ready               [1s]
├── static/...
├── _next/...
├── index.html
└── ...
> Success! Deployment ready [6s]
```

So I understand why you limit it at 52 chars, because you append the `-<hash>` (which is ten characters including the hypen) to the end of the deployment name and you don't want to exceed 63 chars due to DNS limits.

What I would like improved is:

- Provide a better error message to properly indicate what really went wrong with the deployment.
- Document the 52 character limit on the name property in the documentation at https://zeit.co/docs/v2/deployments/configuration/#name

Thank you

**Comment by michaellopez** [comment] 2019-01-25 06:34
Also, this is a v2 only thing. v1 accepts the deployment but truncates the URL automatically.

```sh
# 55 chars
$ now --static -T weahead -t <token> ./out -n 1234567890123456789012345678901234567890123456789012345
> WARN! Your project is missing a now.json file with a `version` property. More: https://zeit.co/docs/version-config
> WARN! You are using an old version of the Now Platform. More: https://zeit.co/docs/v1-upgrade
> Deploying ~/out under weahead
> Using project 1234567890123456789012345678901234567890123456789012345
> https://1234567890123456789012345678901234567890123456789012-<hash>.now.sh [v1] [in clipboard] [6s]
> Deployment complete!
```

The auto-truncation creates another problem though, it makes CI unable to automatically clean up any deployments that are not desired anymore (like upon merge of a PR):

```sh
$ now rm -T weahead -t <token> -y 1234567890123456789012345678901234567890123456789012345
> Could not find any deployments matching "1234567890123456789012345678901234567890123456789012345". Run `now ls` to list.

$ now ls
> X total deployments found under weahead [372ms]
> To list more deployments for an app run `now ls [app]`

  project                                                 url                                                                       inst #    type      state    age
  1234567890123456789012345678901234567890123456789012    1234567890123456789012345678901234567890123456789012-<hash>.now.sh         -    STATIC    READY    5m
```
The current v1 approach that auto truncates can possibly overwrite other deployments that happen to match the same first 52 characters in deployment name. I like the v2 approach better, to fail if the deployment name is too long (but of course with a proper error message and documentation).

**Comment by TooTallNate** [comment] 2019-08-15 23:51
Closing because the correct error message is now displayed:

```
> Error! Failed to validate now.json: Invalid request: name should NOT be longer than 52 characters
Documentation: https://zeit.co/docs/v2/deployments/configuration/
```

**Closed as completed by TooTallNate** 2019-08-15 23:51 UTC
Labels: triaged: bug
