### ISSUE TITLE
Different routes behavior between `now dev` and actual deployment

### ISSUE THREAD

**Issue by huv1k** [vercel/vercel#2953] opened 2019-09-04 14:13 UTC
There is different behavior between `now dev` and actual deployment. When using this config:
```json
{
  "version": 2,
  "builds": [
    { "src": "packages/web-app/package.json", "use": "@now/next" }
  ],
  "routes": [
    { "src": "/(.*)", "dest": "/packages/web-app/$1" }
  ]
}
```
It works correctly in `now dev`, but deployed to Now it's not working with `/test` for example. It throws `404` even that it's valid path. There should be between deployed application and local dev setup. 

Example: https://with-yarn-workspaces.huv1k.now.sh
It's public, so everybody can inspect it.

**Comment by TooTallNate** [comment] 2019-09-04 21:16
Deployment doesn't seem to be public 🤔 

But also, this is a duplicate of #2654.

**Closed as completed by TooTallNate** 2019-09-04 21:16 UTC
