### ISSUE TITLE
How to deploy wordpress with now-php ? 

### ISSUE THREAD

**Issue by fydy** [vercel/vercel#3379] opened 2019-12-04 09:51 UTC
How to deploy wordpress with now-php ?

**Comment by styfle** [comment] 2019-12-05 15:44
Hi @fydy 

We don't maintain `now-php` here.

It is maintained by the community in this repository: https://github.com/juicyfx/now-php

Closing as a duplicate of https://github.com/juicyfx/now-php/issues/33

**Closed as completed by styfle** 2019-12-05 15:44 UTC
