### ISSUE TITLE
Only run `yarn` if `package.json` changes

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2899] opened 2019-08-28 12:38 UTC
When changing a file in a simple project with a Node.js serverless function in `api`, we're running the installation of dependencies every time a file changes.

Instead, we should only run it if `package.json` or a lockfile changes.

```
> Building @now/node@latest:api/index.js
downloading user files...
download complete [0ms]
installing dependencies for user's code...
missing `engines` in `package.json`, using default range: 8.10.x
installing to /Users/rauchg/Projects/test-now/api
yarn install v1.15.2
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.03s.
install complete [347ms]
running user script...
script complete [0ms]
tracing input files...
trace complete [1ms]
```

**Comment by TooTallNate** [comment] 2019-08-30 01:32
This is a duplicate of https://github.com/zeit/now/issues/2605.

**Closed as completed by TooTallNate** 2019-08-30 01:32 UTC
Labels: triaged: bug, area: cli
