### ISSUE TITLE
'list' object has no attribute 'encode' in now__handler__python.py

### ISSUE THREAD

**Issue by Xarrow** [vercel/vercel#2526] opened 2019-07-10 03:43 UTC
In Python sanic ,visit web site via nginx proxy , i found an exception happened in now_handler_python.py . Full message in detail as below ,

```bash
START RequestId: cbb87f5c-035c-4056-a2a1-7d6f185ef97d Version: $LATEST
'list' object has no attribute 'encode': AttributeError
Traceback (most recent call last):
File "/var/task/nowhandlerpython.py", line 234, in now_handler
'headers': [[k.lower().encode(), v.encode()] for k, v in headers.items()],
File "/var/task/nowhandlerpython.py", line 234, in <listcomp>
'headers': [[k.lower().encode(), v.encode()] for k, v in headers.items()],
AttributeError: 'list' object has no attribute 'encode'
```

And  part configuration in nginx as below ,
```bash
proxy_set_header  Accept-Encoding   "";
proxy_set_header  Accept-Language   "zh-CN";
proxy_set_header  Referer           "$simplebox , $http_referer";
proxy_set_header  X-Real-IP         $remote_addr;
proxy_set_header  User-Agent        $http_user_agent;
```
Through multiple  tries , i found `proxy_set_header  Accept-Language   "zh-CN";`  is key point.

**Comment by paulogdm** [comment] 2020-04-06 22:28
Hello,

Please provide a minimal reproducible example and reach out to support@zeit.co so we can assist you better.

I am closing this issue since we don't have actionable items in this thread.

**Closed as completed by paulogdm** 2020-04-06 22:28 UTC
Labels: triaged: bug
