### ISSUE TITLE
"Error! Your deployment failed. Please retry later."

### ISSUE THREAD

**Issue by ChrisBAshton** [vercel/vercel#2778] opened 2019-08-15 21:56 UTC
As of version 16.1.1, my deployments have started failing with:

`> Error! Your deployment failed. Please retry later. More: https://err.sh/now-cli/deployment-error`

I'm unable to see any further error information, so it's difficult to fix!

Here's my now.json:

```json
{
  "version": 2,
  "builds": [
    { "src": "next.config.js", "use": "@now/next" },
    { "src": "dist/*", "use": "@now/static", "config": { "distDir": "output" } }
  ],
  "routes": [
    {
      "src": "^/s(?<season>[0-9]+)/e(?<episode>[0-9]+)/(?<time>.+)",
      "dest": "/index?season=$season&episode=$episode&time=$time"
    },
    {
      "src": "^/s(?<season>[0-9]+)/e(?<episode>[0-9]+)",
      "dest": "/index?season=$season&episode=$episode"
    },
    {
      "src": "^/s(?<season>[0-9]+)",
      "dest": "/index?season=$season"
    }
  ]
}
```

**Comment by TooTallNate** [comment] 2019-08-15 23:10
Hey there @ChrisBAshton, I'm sorry that this is happening to you! Can you confirm if reverting back to an older version fixes the issue for you? Also would it be possible to share standalone repo that makes this error happen so that we can take a closer look? Thanks in advance!

**Comment by solinad21** [comment] 2019-08-16 03:32
i have the same problem...

**Comment by ChrisBAshton** [comment] 2019-08-16 17:36
Hi - turns out the issue was I was trying to upload 5 GB of images! Removing the images and running `now` fixed my deployment.

Won't be an issue for now, but eventually I do anticipate having that many assets across the whole site - any advice on how to do that?

**Comment by leo** [comment] 2019-08-18 11:55
@TooTallNate Can we show a better error for this? It seems like it's a size issue?

**Comment by maiah** [comment] 2019-08-19 01:08
Having the same issue with just next.js repo and a single api inside `/page/api` :(

**Comment by akshaykashid13** [comment] 2019-08-19 12:25
Having the same problem with Node Express Back end and HTML for front end.

**Comment by leo** [comment] 2019-08-19 21:23
@maiah @akshaykashid13 Are any large files (bigger than 1GB) located in your project?

**Comment by maestroDever** [comment] 2019-08-20 20:21
I am having problems with my Nuxtjs project. Last successful deployment was 9 days ago.
It says "Your deployment failed. Please retry later."
On zeit.co dashboard I got this log.
![image](https://user-images.githubusercontent.com/48345279/63381317-191d1c80-c3a1-11e9-9dcb-99a0418cca26.png)
Seems like node version causes this issue... 
Is this the platform related? Or am I doing something wrong? 
It used to be working and I can assure you that I didn't change anything on my project. :(

**Comment by leo** [comment] 2019-08-21 11:59
@maestroDever Is there a `now.json` in your project? If so, does it have `builds`?

**Comment by maestroDever** [comment] 2019-08-21 12:14
@leo Yes, below is the `now.json` file in the project root folder.
```
{
  "version": 2,
  "builds": [
    {
      "src": "nuxt.config.js",
      "use": "@nuxtjs/now-builder",
      "config": {}
    }
  ]
}
```

**Comment by leo** [comment] 2019-08-21 18:53
@maestroDever So, it appears that Nuxt.js bumped their requirement to Node.js 8.12, and we only offer Node.js 8.10 and Node.js 10.

In turn, you can upgrade your Node.js [like this](http://zeit.co/blog/node-10) in order for it to work again.

**Comment by maestroDever** [comment] 2019-08-21 19:47
Seems like I can't use Node 10 because of [this issue](https://github.com/zeit/now-builders/issues/834)

The project was scaffolded 2 weeks ago and latest nuxt release was **yesterday**. https://github.com/nuxt/nuxt.js/releases

`now` build worked until 2 days ago. So it is obvious that the issue is related with **nuxt@2.9.1** - the new release!

I managed to solve this issue by using **nuxt@2.8.1** which was released more than a month ago.

**Comment by akshaykashid13** [comment] 2019-08-24 06:39
> @maiah @akshaykashid13 Are any large files (bigger than 1GB) located in your project?

Nop ! my project is around 26 Mb in size

**Comment by ChrisBAshton** [comment] 2019-08-27 06:42
No longer getting this message as of v16.1.2. But I get this instead:

> Error! Build failed
> Error! Check your logs

And here are the logs:

```
> next build
--
Aug 27 2019 07:35:07:476 | ...next.config.js | Creating an optimized production build ...
Aug 27 2019 07:35:08:702 | ...next.config.js | > Using external babel configuration
Aug 27 2019 07:35:08:702 | ...next.config.js | > Location: "/tmp/201d5570/.babelrc"
Aug 27 2019 07:35:15:638 | ...next.config.js | Compiled successfully.
Aug 27 2019 07:35:15:639 | ...next.config.js | ┌ /
Aug 27 2019 07:35:15:639 | ...next.config.js | ├ /_app
Aug 27 2019 07:35:15:639 | ...next.config.js | ├ /_document
Aug 27 2019 07:35:15:639 | ...next.config.js | ├ /_error
Aug 27 2019 07:35:15:639 | ...next.config.js | └ /random
Aug 27 2019 07:35:15:727 | ...next.config.js | preparing lambda files...
Aug 27 2019 07:35:15:800 | ...next.config.js | Creating lambda for page: "_error.js"...: 57.520ms
Aug 27 2019 07:35:15:959 | ...next.config.js | Creating lambda for page: "random.js"...: 214.844ms
Aug 27 2019 07:35:15:970 | ...next.config.js | Creating lambda for page: "index.js"...: 226.231ms
Aug 27 2019 07:36:02:400 | ...next.config.js | worker exited with code null and signal SIGKILL
Aug 27 2019 07:36:02:432 | ...next.config.js | done
Aug 27 2019 07:36:05:002 | ...next.config.js | done
```

This happened at the 4.13 GB (1,137 items) mark (my web project is a searchable directory of gifs). It got to the point where I was adding ~50 images per deployment, so that the sync step of the upload wouldn't fail, but now I can't even add them 1 at a time.

1,136 items deployed ok but at 1137 it looks like I've hit some undocumented limit? Have tried re-deploying several times but keeps failing on this. Any advice appreciated!

**Comment by leo** [comment] 2019-08-27 14:19
Thanks for sharing this, @ChrisBAshton!

It seems like there is a circumstance under which your deployment will error, without us even telling you why exactly (the logs don't indicate that).

I'll have someone from the Infra team look into this matter for you.

**Comment by ChrisBAshton** [comment] 2019-08-28 07:36
Thanks @leo - let me know if I can provide any info to help the infra team. Currently unable to make any more deployments so keen to get this sorted!

The repos aren't public, but I can forward some more details privately.

**Comment by leo** [comment] 2019-08-30 09:50
Thanks! @joecohens will take a look at this.

**Comment by silvio-e** [comment] 2019-08-30 19:58
@leo Upgrade to node 10.x doesn't work for me.

Error persists and the error log just changes to: `Expected version "10.x". Got "8.10.0"`

I got just so happy that now 2 is working with nuxt like before now 1 - just with one command hassle free and now that. Ok, it's not really your fault - but that the nuxt builder doesn't support node 10.x caused me already some weeks ago a headache as I wanted to use a package which needs it. Sorry for the included frustration of the recent months...

Could you indicate when the nuxt builder will support node 10.x?

**Comment by leo** [comment] 2019-09-05 12:04
@silvio-e Thank you for investigating this!

Can you please open an issue on the [builder repo](https://github.com/nuxt/now-builder) for this? I'm sure we will then know when Node.js 10 support will be added.

**Comment by ChrisBAshton** [comment] 2019-09-05 16:11
> Thanks! @joecohens will take a look at this.

Hi both - do you know when this will be looked into? Thanks in advance!

**Comment by leo** [comment] 2019-09-05 18:50
@joecohens will take a look at this very soon. Thanks for staying tuned!

**Comment by trek** [comment] 2024-08-26 13:40
Hi @ChrisBAshton,

Thank you for the bug report. We're closing out older issues that have probably been addressed by now.

**Closed as completed by trek** 2024-08-26 13:40 UTC
Labels: triaged: bug
