### ISSUE TITLE
request: support deploying "stacks" via docker compose

### ISSUE THREAD

**Issue by leo** [vercel/vercel#763] opened 2017-09-01 22:25 UTC
_From @jeffreywescott on August 14, 2017 6:41_

Loving now (and Next.js, too). Thanks for all of the hard work.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Context

It's awesome that Now lets you deploy a Dockerfile. However, it would be amazing if you supported deploying a whole "stack" for an app via a set of `docker-compose.yml` (and similar) files.

Any plans to support such a scenario? It would be pretty amazing to have all of the load balancing and DNS handled by the standard Now stuff without having to resort to something like DigitalOcean and `docker-machine.

_Copied from original issue: zeit/now#50_

**Comment by leo** [comment] 2017-09-01 22:25
_From @gandulio on August 15, 2017 1:53_

Please add this!

**Comment by einarpersson** [comment] 2017-10-10 07:47
+1

**Comment by Qix-** [comment] 2017-11-10 17:45
We definitely have some ideas for this. Stay tuned :)

**Comment by jeffreywescott** [comment] 2017-11-30 05:03
So glad to see this is being looked at!

**Comment by schickling** [comment] 2018-05-05 20:49
Very tuned! 📻

**Comment by styfle** [comment] 2018-05-10 21:13
This looks like a duplicate of #294

**Closed as completed** 2018-11-13 12:22 UTC
Labels: triaged: feature request
