### ISSUE TITLE
TypeErrorf.ref(now.dist:index)

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2732] opened 2019-08-09 09:39 UTC
Check out [this error](https://sentry.io/organizations/zeithq/issues/1134197735/?referrer=slack):

![image](https://user-images.githubusercontent.com/6170607/62769939-48c34f00-ba9a-11e9-87c2-8aafa669727f.png)

**Comment by TooTallNate** [comment] 2019-08-09 17:20
This is a duplicate of #2711, and has already been fixed.

**Closed as completed by TooTallNate** 2019-08-09 17:20 UTC
Labels: triaged: bug

**Comment by leo** [comment] 2019-08-09 17:33
Amazing!
