### ISSUE TITLE
now dev - throwing 404 on subdirectories containing .html files

### ISSUE THREAD

**Issue by holgerino** [vercel/vercel#2362] opened 2019-05-18 14:00 UTC
Deploying static files with a now.json like 
```json 
{
  "version": 2
}
```
and a directory like 
```
- /
 now.json
 index.html
   - pages
   other.html
``` 
while linking to `other.html` from `index.html`
will work deploying with now but results in a 404 page when testing locally with now dev.

**Comment by TooTallNate** [comment] 2019-08-13 21:58
Closing because I can not reproduce this using the latest version of Now CLI. Repro repository is here: https://github.com/TooTallNate/now-cli-2362

Please create a new issue if you are still having any problems.

**Closed as completed by TooTallNate** 2019-08-13 21:58 UTC
