### ISSUE TITLE
.nowignore is failing for subdirs 

### ISSUE THREAD

**Issue by paulogdm** [vercel/vercel#1990] opened 2019-03-19 20:48 UTC
## Summary

There is a bug with `.nowignore`. Unfortunately, it is failing for nested directories.

## Reproduction Steps

1. Create a simple `next.js` example.
2. Create a `.nowignore` with:
```
node_modules
static/img/
```
3. Put content on `static` and `static/img`>
4. `now`

## Expected Behavior

`/static/img/` should not be uploaded.

## Deployment

https://pedalsmarts-lean-6jm9m8bok.now.sh/_src

**Comment by juliangruber** [comment] 2019-03-20 07:07
closing as duplicate of https://github.com/zeit/now-cli/issues/1717#issuecomment-469736560

**Closed as completed by juliangruber** 2019-03-20 07:07 UTC
Labels: triaged: bug
