### ISSUE TITLE
Cli is not responding at all

### ISSUE THREAD

**Issue by wunnle** [vercel/vercel#1923] opened 2019-03-02 13:37 UTC
I'm having an issue with now-cli. After installation now command (or any other like now -v) is not producing any output. I'm attaching a screenshot.

Using 14.0.2 on Windows 10

![4df8e395-571f-4887-99ba-915f6e250713 png](https://user-images.githubusercontent.com/1238178/53682704-80161e80-3cf8-11e9-8333-3ff167676131.jpg)

**Comment by rivy** [comment] 2019-03-02 18:59
TLDR; "now\download\dist\now" is missing/empty.

### Additional info

When installed via `yarn`, the "now.cmd" file contains:

```
@"%~dp0\..\..\..\..\..\Yarn\Data\global\node_modules\.bin\now.cmd"   %*
```

That ".bin\now.cmd" file then uses `node` to run "%~dp0\..\now\download\dist\now", but that final file is completely empty:

```
C:>msls -Al node_modules\now\download\dist
total 32M
-rw------a  1 Roy              572k Mar  2 12:40 index.js
-rw------a  1 Roy                 0 Mar  2 12:46 now
-rwx-----a  1 Roy               31M Mar  2 12:46 now.exe*
```

**Comment by rivy** [comment] 2019-03-02 19:20
Using [`scoop`](https://github.com/lukesampson/scoop) ...

```
C:\>scoop install "https://raw.githubusercontent.com/rivy/scoop-bucket/master/now.json"
```

This installs "now-win.exe", from the "now-cli" github repo, as both `now-win` and `now`.

**Comment by wunnle** [comment] 2019-03-02 23:25
> Using [`scoop`](https://github.com/lukesampson/scoop) ...
> 
> ```
> C:\>scoop install "https://raw.githubusercontent.com/rivy/scoop-bucket/master/now.json"
> ```
> This installs "now-win.exe", from the "now-cli" github repo, as both `now-win` and `now`.

rivy, this solves the problem but looks like an interesting solution, I think the bug still exists when installing cli the regular way.

BTW now getting an error about my email which is perfectly valid, but this needs its own thread I guess.

**Comment by rivy** [comment] 2019-03-03 03:04
@wunnle , yep, this is is just a personal workaround, but it appears that a working fix is in progress (see #1922). I'm not sure of the timeline for the merge, but this will work until the merge occurs.

**Comment by danielschmitz** [comment] 2019-03-03 12:21
`npm install -g now@13.1.3` while #1922 don't comes

**Closed as completed** 2019-03-03 15:48 UTC

**Comment by albertosantini** [comment] 2019-03-04 09:35
In `14.0.3` I see the same issue.

**Comment by albertosantini** [comment] 2019-03-04 09:41
`now` is empty.
```
$ ll /c/Users/alberto.santini/AppData/Roaming/npm/node_modules/now/download/dist/
total 20M
-rw-r--r-- 1 alberto.santini 573K Oct 26  1985 index.js
drwxr-xr-x 1 alberto.santini    0 Mar  4 10:32 ../
-rwxr-xr-x 1 alberto.santini  32M Mar  4 10:32 now.exe*
-rw-r--r-- 1 alberto.santini    0 Mar  4 10:32 now
drwxr-xr-x 1 alberto.santini    0 Mar  4 10:32 ./
```

And a minor detail for `/c/Users/alberto.santini/AppData/Roaming/npm/now`.
The first lines are repeated.

```
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/node_modules/now/download/dist/now.exe" "$@"
  ret=$?
else 
  node  "$basedir/node_modules/now/download/dist/now" "$@"
  ret=$?
fi
exit $ret
```

**Comment by albertosantini** [comment] 2019-03-04 09:47
Also `now@14.1.0-canary.4` has the same issue.

**Comment by albertosantini** [comment] 2019-03-04 09:49
@AndyBitz please, shall you give another look at the issue, because it seems I can reproduce it with the latest stable and canary?

**Comment by albertosantini** [comment] 2019-03-16 06:48
I see the same issue with `14.1.0` under git bash.

**Comment by NonPolynomial** [comment] 2019-03-22 11:05
Same issue with `14.2.3` under git bash.

**Comment by albertosantini** [comment] 2019-05-07 06:56
Here it works with now 15.2.0 via #2322.

**Comment by Talii123** [comment] 2019-05-21 23:10
I just updated to 15.3.0 and am still having this problem - both in Powershell and Git Bash.
