### ISSUE TITLE
now dev takes a long time to reload

### ISSUE THREAD

**Issue by elie222** [vercel/vercel#2319] opened 2019-05-05 09:54 UTC
I have a project written in 150 lines of TypeScript and `now dev` takes a long time to reload. Sometimes 10 seconds+.

The project is a single file that imports `axios`, `cheerio`, and `googleapis`.

**Comment by elie222** [comment] 2019-05-05 10:12
This may deserve a new issue, but I'm also seeing this happening every 5-10 hot reloads:

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

**Comment by maxbeatty** [comment] 2019-05-06 20:35
I am also seeing incredibly slow build times. These lines stuck out to me when running `DEBUG=* now dev`:

```
 @zeit/fun:runtimes Runtime 'nodejs8.10' is already initialized at '/Users/max/Library/Caches/co.zeit.fun/runtimes/nodejs8.10' +46s
 @zeit/fun:index Creating provider 'NativeProvider' +46s
 @zeit/fun:unzip Unzipping buffer (length=1629090) to temp dir '/var/folders/g4/1sg6rxt10gd8nt_bkhpb09jm0000gn/T/zeit-fun-4a394dc55a43a' +46s
```

Happy to provide more detail to help

**Comment by GaelS** [comment] 2019-05-14 07:36
I am experiencing the same issue. Beside, I think that any serverless function is recompiled, even though no files related to this specific function have been changed, between two uses. 

Those two problems slow down the development process. I know `now dev` is still in beta but as of today, is it the expected behavior or I am doing something wrong ?

Despite that, thank you for the great work  !

**Comment by Janpot** [comment] 2019-05-18 15:02
> This may deserve a new issue, but I'm also seeing this happening every 5-10 hot reloads:
> 
> ```
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
> ```

Seeing the same, on a small handler, that is only importing `googleapis` and `node-fetch`. I guess it's `googleapis` not playing well with `now dev`

**Comment by elie222** [comment] 2019-05-18 17:51
I was also using googleapis. And I believe axios.

**Comment by leo** [comment] 2019-05-30 15:28
This issue was resolved with the latest version of Now CLI.

Let me know if you're still experiencing problems, then we'll re-open this. 🙏

**Closed as completed by leo** 2019-05-30 15:28 UTC

**Comment by kiranps** [comment] 2019-06-02 15:24
@elie222  @GaelS @leo @Janpot  if caching is disabled in chrome devtools network tab for every api calls it will issue a rebuild

**Comment by elie222** [comment] 2019-06-02 23:35
I have caching enabled in Chrome dev tools.

What was the issue? I am on 15.3.0 and `now dev` is far from running smoothly.

**Comment by ywg-jean** [comment] 2019-06-17 21:18
@leo I'm afraid the issue is still here : 
```
> Building @now/node:api/subscriptions/index.js
downloading user files...
installing dependencies for user's code...
installing to /Users/jean/dev/nowslow/api/subscriptions
running user script...
compiling entrypoint with ncc...
ncc: Module directory "/Users/jean/dev/nowslow/node_modules/hash-stream-validation" attempted to require "fast-crc32c" but could not be resolved, assuming external.
ncc: Module directory "/Users/jean/dev/nowslow/node_modules/write-file-atomic" attempted to require "worker_threads" but could not be resolved, assuming external.
ncc: Module directory "/Users/jean/dev/nowslow/node_modules/bytebuffer/dist" attempted to require "memcpy" but could not be resolved, assuming external.
  @zeit/fun:runtimes Runtime 'nodejs8.10' is already initialized at '/Users/jean/Library/Caches/co.zeit.fun/runtimes/nodejs8.10' +2m
  @zeit/fun:index Creating provider 'NativeProvider' +24s
```

```
$ now --version
15.5.0
$ ncc version
0.18.5
```
I have yet to figure out how to force the now-cli 15.5.0 to use ncc 0.19.x

**Comment by TooTallNate** [comment] 2019-06-17 21:29
@ywg-jean The version of ncc is tied to the [`@now/node` builder code](https://github.com/zeit/now-builders/blob/canary/packages/now-node/package.json). Please create a new issue describing the issue 🙏

**Comment by ywg-jean** [comment] 2019-06-17 21:46
@TooTallNate it's unclear : are you asking me to open an issue to ask for a way to configure the version of ncc or to open a new issue for slow build time ?

If the latter I'm not sure why since what I am observing has the same symptoms as what @elie222 described initially (including the OOM errors) and has somewhat similar logs as those reported by @maxbeatty  
Do you really recommand opening a different issue ?
