### ISSUE TITLE
now ls error if no deployments exists

### ISSUE THREAD

**Issue by kandros** [vercel/vercel#475] opened 2017-05-01 22:22 UTC
`now ls` with no deployments on that team
```
 Error! Unknown error: TypeError: Cannot read property 'deploymentId' of undefined
TypeError: Cannot read property 'deploymentId' of undefined
    at /usr/local/lib/node_modules/now/build/bin/now-list.js:117:48
    at Generator.next (<anonymous>)
    at c (/usr/local/lib/node_modules/now/build/bin/now-list.js:254:99)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

now version 5.0.0

**Comment by jamo** [comment] 2017-05-01 23:39
Duplicate of #471

**Closed as completed by jamo** 2017-05-01 23:39 UTC
