### ISSUE TITLE
`now dev`: every call to /api initiates a new build

### ISSUE THREAD

**Issue by sergeyfilimonov** [vercel/vercel#3066] opened 2019-09-24 13:41 UTC
In `now.json` I have:

```json
{
  "name": "project",
  "version": 2,
  "github": {
    "enabled": true
  },
  "routes": [
    { "handle": "filesystem" },
    { "src": "/.*", "status": 404, "dest": "404" }
  ],
  "builds": [
    {
      "src": "package.json",
      "use": "@now/static-build",
      "config": { "distDir": "dist" }
    },
    {
      "src": "api/actions/lead/register/index.js",
      "use": "@now/node"
    },
    {
      "src": "api/index.js",
      "use": "@now/node"
    }
  ],
  "env": {
    "MONGO_URI": "@mongo_uri",
    "SLACK_API_KEY": "@slack_api_key"
  }
}
```
In `package.json`:

```json
"scripts": {
    "build": "gridsome build",
    "develop": "gridsome develop",
    "explore": "gridsome explore",
    "now-build": "npm run build"
  }
```

When I run `now dev` it initiates `gridsome develop` and serves a local static Gridsome website. But once I try to call some route within `/api` it goes `yarn run now-build`.

What am I doing wrong?

`now --prod` seems to be working but it also initiates `gridsome build` for three times and after adding /api to the project the deployment process started taking much longer time.

**Comment by leo** [comment] 2019-09-25 22:27
Thank you for reporting this! We'll take a look.

**Comment by TooTallNate** [comment] 2019-09-26 00:55
This is expected behavior. Both the `@now/node` and `@now/next` builders look for the closest `package.json` file and execute the "now-build" script if it is defined. So to fix this, you need to create an `api/package.json` file. This is actually better because now your API endpoints will only install the dependencies that they use and not the ones that your frontend uses and vice versa.

I'm gonna close this one, but feel free to comment if we need to clarify anything more.

**Closed as completed by TooTallNate** 2019-09-26 00:55 UTC
Labels: area: cli

**Comment by sergeyfilimonov** [comment] 2019-09-26 07:18
@TooTallNate thank you for the answer! Adding `package.json` and modules to `/api` is indeed a nice idea as I separate client and backend modules. Although all this is still odd because `package.json` as a source is explicit only in one build.  It seems the Now team should still investigate into this issue.

**Comment by sergeyfilimonov** [comment] 2019-10-13 13:49
@TooTallNate @leo could you please advise me on how to setup the project properly. I've tried adding the second `project.json` into the `api` folder but it got even more confusing.. I have the following file structure:

```
- api
-- _use
-- actions
-- package.json
...
now.json
package.json
```

`now.json`:
```json
{
  "name": "NAME",
  "scope": "SCOPE",
  "github": { "enabled": false },
  "routes": [
    { "handle": "filesystem" },
    { "src": "/.*", "status": 404, "dest": "404" }
  ],
  "builds": [
    {
      "src": "package.json",
      "use": "@now/static-build",
      "config": { "distDir": "dist" }
    },
    {
      "src": "api/actions/**/*.js",
      "use": "@now/node"
    }
  ]
}
```

`package.json`:
```json
{
  "name": "website",
  "private": true,
  "scripts": {
    "dev": "gridsome develop -p 5002",
    "stage": "now",
    "prod": "now --prod",
    "build": "gridsome build",
    "explore": "gridsome explore",
    "now-build": "npm run build"
  },
  "dependencies": {
    ...
  },
  "devDependencies": {
    ...
  }
}
```

`api/package.json`:
```json
{
  "name": "api",
  "private": true,
  "scripts": {
    "build": "node",
    "now-build": "npm run build"
  },
  "dependencies": {
    ...
  },
  "devDependencies": {
    ...
  }
}
```

So after a go `now dev` it shows an error `No output directory named "public" found.`
