### ISSUE TITLE
Error adding certain DNS SRV records

### ISSUE THREAD

**Issue by jaydenseric** [vercel/vercel#1549] opened 2018-08-24 07:39 UTC
While attempting to [setup FastMail](https://gist.github.com/jaydenseric/c68cba49246881d0266d135c9583c5b4), the following commands don't work:

```
now dns add enamor.app _imap._tcp SRV 0 0 0 .
now dns add enamor.app _pop3._tcp SRV 0 0 0 .
now dns add enamor.app _carddav._tcp SRV 0 0 0 .
now dns add enamor.app _caldav._tcp SRV 0 0 0 .
```

They result in an error like this:

<img width="602" alt="screen shot 2018-08-24 at 5 16 14 pm" src="https://user-images.githubusercontent.com/1754873/44571607-8fa23100-a7c4-11e8-8c36-dd469eff091e.png">

I remember discussing this bug with the Zeit team in Slack, a few months ago, but the chat history is gone now and I can't remember an outcome.

**Comment by jaydenseric** [comment] 2018-08-24 16:37
Here is the purpose of this type of record, from FastMail support (received back in January):

> Hi Jayden,
>
> Thank you for writing to us.
>
> > Are there any benefits to having these entries present, and if not, should they be removed from the FastMail DNS docs? If they are useful the Zeit engineers will try to add support.
>
> With SRV RRs it is possible to indicate that a particular service is not supported at all at a particular domain by setting the target of an SRV RR to ".". If such records are present, clients MUST assume that the specified service is not available, and instead make use of the other SRV RRs for the purposes of determining the domain preference.
>
> Example: service records for IMAP and POP3 with both TLS and non-TLS service types are present. Both IMAP and POP3 non-TLS service types are marked as not available. IMAP (with TLS) has a lower-numbered priority value 0 than POP3 (with TLS) at priority 10, indicating to the MUA that IMAP is preferred over POP3, when the MUA can support either service, and only the TLS versions of the services are available.
>
>_imap._tcp SRV 0 0 0 .
>_imaps._tcp SRV 0 1 993 imap.example.com.
>_pop3._tcp SRV 0 0 0 .
>_pop3s._tcp SRV 10 1 995 pop3.example.com.
>------------
>
>Hope this clarifies your concern. Let me know if you have any questions.

**Comment by OlliV** [comment] 2018-08-24 17:01
It's not a bug but an unsupported feature. Our upstream provider doesn't support these records. What would happen if these records don't exist? Is there an example of a a software that can't find the TLS records if the non-encrypted records don't exist?

**Comment by leo** [comment] 2018-11-13 13:52
Closing this, now that we didn't receive a response in 3 months.

**Closed as completed by leo** 2018-11-13 13:52 UTC
