### ISSUE TITLE
I can't copy paste credit card number.

### ISSUE THREAD

**Issue by raneio** [vercel/vercel#317] opened 2017-02-15 15:07 UTC
now cc add
\> Enter your card details
✓ Name        Foo Bar
\- Number      4111 1111 1111 111u ndef ined #### #### #### ###

**Comment by leo** [comment] 2017-03-17 09:18
@matheuss Should be an easy fast fix right? Can you tackle this?

**Comment by TooTallNate** [comment] 2019-08-14 21:58
Closing because I can not reproduce this using the latest Now CLI.

**Closed as completed by TooTallNate** 2019-08-14 21:58 UTC
Labels: triaged: bug
