### ISSUE TITLE
now in windows only outputs time

### ISSUE THREAD

**Issue by barbalex** [vercel/vercel#2003] opened 2019-03-21 09:29 UTC
I am using windows 10, up to date.

```
alex@SURFACE-ALEX C:\Users\alex\gs3\public
$ now

Thu Mar 21 10:28:20 2019
```

This is a brand new pc. I have never installed any other now module.

How can I get now-cli to work?

**Comment by juliangruber** [comment] 2019-03-21 12:08
How did you install Now CLI?

**Comment by barbalex** [comment] 2019-03-21 13:39
`npm i -g now`

**Comment by barbalex** [comment] 2019-03-21 13:56
This happens both on my desktop pc and my notebook

**Comment by juliangruber** [comment] 2019-03-21 13:58
This looks like an issue with your npm setup. You could try fixing that by googling for windows npm issues, or use one of the other installation methods outlined here: https://zeit.co/download#now-cli.

**Comment by barbalex** [comment] 2019-03-21 14:02
> This looks like an issue with your npm setup

Other globally installed npm modules work. But you are probably right there. It is weird though that it happens on _both_ my pc and my freshly installed notebook.

>  use one of the other installation methods outlined here: https://zeit.co/download#now-cli

I had installed the exe. A few issues I've had:

- I could not use the command line either. I think for the same reason
- I do not see any value in the .exe. Besides from cluttering my UI (it works on my mac but only gets in my way there). All I need is the command line

**Comment by juliangruber** [comment] 2019-03-21 18:22
Can you please try this? https://stackoverflow.com/a/27864253

**Comment by fu-sen** [comment] 2019-03-22 05:09
Did you use Git bash? (I notice it at the prompt)
If that is correct, I feel that .bashrc and .profile in the home folder are replacing the now command.

Git bash on Windows is currently reporting some bugs, See also other issues.
You should use Powershell or cmd instead.

**Comment by barbalex** [comment] 2019-03-22 08:23
@juliangruber that did not hep as `C:\Program Files\nodejs` was already included

**Comment by barbalex** [comment] 2019-03-22 08:26
@fu-sen I am using ConEmu console, that is why it looks like git bash.

I have same result in powershell.

Using ubuntu on windows is actually my only way to correctly run now on both my windows pc's right now.

**Comment by prKassad** [comment] 2019-05-10 18:43
+1, same problem on Win10. I use PowerShell and tried different versions nodejs.

```
PS C:\projects\zeit-test> now

Fri May 10 23:39:09 2019
PS C:\projects\zeit-test> now help

Fri May 10 23:39:14 2019 -- help
```

**Comment by prKassad** [comment] 2019-05-10 18:53
If run now cli from path with global npm modules then nothing happens:

```
PS C:\projects\zeit-test> C:\nodejs\npm\now.cmd
PS C:\projects\zeit-test> C:\nodejs\npm\now.cmd help
```

**Comment by prKassad** [comment] 2019-05-10 19:07
This worked if run now.exe directly from `C:\nodejs\npm\node_modules\now\download\dist\now.exe`

By default on Windows CMD/PowerShell command `now` return current time.

I added the following alias in my PowerShell profile: 
`Set-Alias now C:\nodejs\npm\node_modules\now\download\dist\now.exe`

And it is worked.

**Comment by TooTallNate** [comment] 2019-08-13 02:36
Closing because I can not reproduce this behavior, and because a valid workaround is documented in this issue for anyone who is experiencing the same.

**Closed as completed by TooTallNate** 2019-08-13 02:36 UTC
