### ISSUE TITLE
[now dev] Next.js + Node builders in monorepo on different ports

### ISSUE THREAD

**Issue by shahruz** [vercel/vercel#2371] opened 2019-05-21 22:06 UTC
This issue is reproducible using the [VRS example](https://github.com/zeit/vrs).

Running now dev on 15.3.0 will make the Node based routes accessible on port 3000, and the Next.js app on port 5000. This change appears to be new in 15.3 (all endpoints were accessible via port 3000 on 15.2).

The routing behind the scenes seems to work fine if I use port 5000, but the console output makes it unclear that the Next.js app is accessible there.

`> Success! Builder setup complete`
`> Ready! Available at http://localhost:3000`

**Comment by skaltenegger** [comment] 2019-05-23 17:36
I can confirm that next only works on port 5000 on 15.3.0.

**Comment by mihaiserban** [comment] 2019-05-29 08:16
> I can confirm that next only works on port 5000 on 15.3.0.

luckily i've seen this issue, never would have guessed it's port 5000

**Comment by seejamescode** [comment] 2019-06-02 02:07
I am also running both a `node` and `next` buildpack. However, everything works on port 3000. My problem is that Next.js tries telling me `ctx.req.headers.host === "localhost:5000"`, but the Node server is only accessible from port 3000.

**Comment by jmillxyz** [comment] 2019-06-11 22:50
Is there documentation on how ports will be allocated for monorepos? I'd like to get a python API talking to my static JS frontend, but I have no idea which port it's using for the backend (I've tried 5000, it's not that). In the example below, `localhost:3000` shows me my static JS + HTML as expected.

`now dev -d` says it's `⠴ Installing builders: @now/python, @now/static`, but when I attempt to hit one of my API endpoints at `localhost:3000/api/example`, this results in the lambda getting built with pip and no actual response:

```
▶ now dev
> Now CLI 15.4.0 dev (beta) — https://zeit.co/feedback/dev
> Ready! Available at http://localhost:3000
> GET /api/example
> Building @now/python:api/example.py
downloading files...
running "pip install --disable-pip-version-check --target . --upgrade werkzeug"...
...
Successfully installed Flask-1.0.3 Jinja2-2.10.1 MarkupSafe-1.1.1 Werkzeug-0.15.4 beautifulsoup4-4.7.1 certifi-2019.3.9 chardet-3.0.4 click-7.0 idna-2.8 itsdangerous-1.1.0 requests-2.22.0 soupsieve-1.9.1 urllib3-1.25.3
entrypoint is api/example.py
```

**Comment by iamstarkov** [comment] 2019-06-17 23:23
same here:

* when deployed "next.js+node lambdas" have the same host
* while `now dev` hosts itself on `localhost:3000` host but node lambdas are on `localhost:5000`

**Comment by TooTallNate** [comment] 2019-08-13 01:56
Closing because the VRS example now works as expected when using `now dev`.

As for the `host` header from within Next.js: you should be using the `x-forwarded-host` header instead.

**Closed as completed by TooTallNate** 2019-08-13 01:56 UTC
