### ISSUE TITLE
getting  Directory Listing after deplpyment

### ISSUE THREAD

**Issue by mohamed-sultan** [vercel/vercel#2327] opened 2019-05-08 07:38 UTC
my next.config.js
const withSass = require("@zeit/next-sass");
module.exports = withSass();
my now.json
{
"name": "oo",
"alias": "next-connect",
"dotenv": true,
"version": 2,
"builds": [{ "src": "server/app.js", "use": "@now/node" }],
"routes": [{ "src": "/(.*)", "dest": "/" }]
}
working on localhost with the expected but when deploy to now i get the listing directory
----------------- my scripts------------------
"dev": "nodemon server/app.js --watch server",
"start": "node server/app.js",
"now-build": "next build",
"deploy": "now --public",
"alias": "now alias",

**Comment by timneutkens** [comment] 2019-05-08 09:25
Duplicate of https://github.com/zeit/next.js/issues/7280

I've asked the support team to have a look at your other issue.

**Closed as completed by timneutkens** 2019-05-08 09:25 UTC
