### ISSUE TITLE
FileBlob.fromStream raise error `Maximum call stack size exceede`

### ISSUE THREAD

**Issue by ragingwind** [vercel/vercel#2861] opened 2019-08-22 12:06 UTC
I've got the error below when I tried to make an example in DEVELOPING_A_BUILDER.md, tml-minifier while test. is this known issue or What did I wrong?

```
RangeError: Maximum call stack size exceeded
        at Function.[Symbol.hasInstance] (<anonymous>)
      at ReadStream (node_modules/@now/build-utils/dist/index.js:14819:14)
      at ReadStream (node_modules/@now/build-utils/dist/index.js:14820:28)
      at ReadStream (node_modules/@now/build-utils/dist/index.js:14820:28)
      at ReadStream (node_modules/@now/build-utils/dist/index.js:14820:28)
      at ReadStream (node_modules/@now/build-utils/dist/index.js:14820:28)
      at ReadStream (node_modules/@now/build-utils/dist/index.js:14820:28)
      at ReadStream (node_modules/@now/build-utils/dist/index.js:14820:28)
      at ReadStream (node_modules/@now/build-utils/dist/index.js:14820:28)
	  ...
```

**Comment by styfle** [comment] 2021-03-04 22:34
If you can shared the code to reproduce the issue, then we can address the issue.

For now, I'm closing since its likely an infinite loop in your code.

**Closed as completed by styfle** 2021-03-04 22:34 UTC
Labels: triaged: bug, area: build-utils
