### ISSUE TITLE
now list has formatting issues on Windows

### ISSUE THREAD

**Issue by cfjedimaster** [vercel/vercel#582] opened 2017-05-25 15:49 UTC
Title says it all pretty much. The issue is with the `inst` column. I see it in both Powershell and CMD. Screen shots:

![image](https://cloud.githubusercontent.com/assets/393660/26458038/c94267a8-4137-11e7-831a-8e9f7fe8fc8f.png)

![image](https://cloud.githubusercontent.com/assets/393660/26458058/d788a390-4137-11e7-9ce7-b177d5131cf8.png)

**Comment by 1jerry** [comment] 2017-06-16 14:20
Just reporting  that it works for me for version 6.4.1-7.0.1.  I am getting either a 1 or 0 in the `inst` column.

[Windows 10]

**Comment by cfjedimaster** [comment] 2017-06-16 14:28
Still broken for me in latest. (Works great in WSL though.)

**Comment by Qix-** [comment] 2017-06-16 22:30
Which version and build of Windows are you running, @cfjedimaster?

**Comment by cfjedimaster** [comment] 2017-06-17 15:37
Windows 10, v 1703. I see this on my laptop (Insiders Build) and desktop (vanilla Win10)

**Comment by leo** [comment] 2018-11-13 17:26
We should definitely fix this!

**Comment by TooTallNate** [comment] 2019-08-09 20:34
<img width="542" alt="Screen Shot 2019-08-09 at 1 33 18 PM" src="https://user-images.githubusercontent.com/71256/62807482-541e7680-baaa-11e9-85bd-4961b9942f86.png">

Closing because I can't reproduce this in `cmd.exe` nor PowerShell. If this is still an issue please let us know and we will take a deeper look.

**Closed as completed by TooTallNate** 2019-08-09 20:34 UTC
Labels: triaged: bug

**Comment by cfjedimaster** [comment] 2019-08-09 20:39
I just tested and can confirm it's all good now.
