### ISSUE TITLE
Feature Request: Addons from CLI

### ISSUE THREAD

**Issue by colinskow** [vercel/vercel#460] opened 2017-04-28 04:51 UTC
I would like the ability to be able to setup external services like Redis or MongoDB from either the command line or a simple web interface like Heroku does.

https://elements.heroku.com/addons

Not only would this make things much easier for developers, but it would bring in extra revenue to your company through vendor commissions.

**Comment by leo** [comment] 2017-05-02 08:22
Duplicate of https://github.com/zeit/now-cli/issues/350 😊

**Closed as completed by leo** 2017-05-02 08:22 UTC
