### ISSUE TITLE
SyntaxError when using mongodb

### ISSUE THREAD

**Issue by TheBeastLT** [vercel/vercel#2053] opened 2019-04-01 09:54 UTC
I'm getting a SyntaxError when using [mongodb@3.2.2](https://www.npmjs.com/package/mongodb) dependency. It works ok on local when i start up a server, but on now prod or using now dev I'm getting:
```
SyntaxError: Unexpected token *
async function* asyncIterator() {
              ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/zeit-fun-03487a6714a2b/launcher.js:9:37)
```

**Comment by victorsmirnov** [comment] 2019-04-03 22:52
I have the same issue with mongodb@3.2.2 and I found that the issue is already reported https://github.com/zeit/now-builders/issues/335
Hope this might help. At least they provide a quick fix for the issue.

**Comment by paulogdm** [comment] 2019-04-21 14:47
Closing in favor of https://github.com/zeit/now-builders/issues/335

**Closed as completed by paulogdm** 2019-04-21 14:47 UTC
