### ISSUE TITLE
Failing deploying a file named 404.html 

### ISSUE THREAD

**Issue by felipenmoura** [vercel/vercel#30] opened 2016-09-14 19:04 UTC
I was deploying a `404.html` file and faced some weird problems!

The deploy was successful, but my service worker was always failing to install due to a fetch failure (for this `404.html` file, which was always not found when the sw tried to fetch it and store it into cache).

I simply renamed the `404.html` into `not-found.html` and it started working normally.

Any idea about the reason for this behaviour?
In my local environment it works with the 404.html file, tried in many different machines and devices, so, I don't think it is a problem with the service worker itself.

Indeed, after deploying, when going for the `/404.html` address in the browser, I got a not found page (the zeit's now 404 page) instead of the (existing??) file named 404.html.

Interestingly enough, the `404.png` file works normally.

**Comment by leo** [comment] 2016-12-12 17:34
https://github.com/zeit/serve/pull/34

**Comment by DonnieWest** [comment] 2017-06-03 22:41
@leo is there any additional info on this? I'm facing the same issue today and not seeing a clear workaround

**Comment by leo** [comment] 2017-06-04 08:29
Hmmm, I honestly haven't faced it personally, so I don't have any additional info for you. Maybe the code needs a fix?

**Comment by DonnieWest** [comment] 2017-06-05 00:36
@leo dunno if this is helpful, but I have replicated it on my personal site that I've migrated over from github pages. You can see the source [here](https://github.com/DonnieWest/donniewest.github.com/commits/source) and commit `51ae1ff8631b5ebdc0ece545c27e39aa045d3e30` fixed the issue for me. I wouldn't mind looking into the issue and submitting a patch, but I'm not sure when I'd be able to do so

**Comment by jackrobertscott** [comment] 2018-02-15 23:58
Hey everyone, I managed (after a deal of time) to work out how to fix it. It was a bit of an effort so I decided to make an article on it for anyone else who gets stuck.

Solved: https://itnext.io/fix-404-error-on-single-page-app-with-zeit-now-b35b8c9eb8fb

**Comment by felipenmoura** [comment] 2018-02-16 02:48
@leo did you get the point of this issue?
That PR you had mentioned hadn't actually much to do with it.
The problem is the file name. If the file being requested is `404.html`, it will deliver the **zeit's 404 page**, not the customised 404.html being requested. When the we simply rename it to anything else, it works.

I thought it had already been fixed as you had closed it, and haven't tried it lately. Am just mentioning it here because I see @jackrobertscott has faced it and brought this issue back to light :)

**Comment by leo** [comment] 2018-02-16 02:55
Oh, I see – got it. We'll try to reproduce it!

**Comment by leo** [comment] 2018-11-08 18:00
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2

**Closed as completed by leo** 2018-11-08 18:00 UTC
