### ISSUE TITLE
OptiPng build error fail

### ISSUE THREAD

**Issue by mingsterism** [vercel/vercel#1914] opened 2019-02-27 04:18 UTC
Hi, 
I'm deploying a static site with this `now.json` settings. 
```
{
  "version": 2,
  "builds": [
    { "src": "index.html", "use": "@now/static" },
    { "src": "images/*.png", "use": "@now/optipng" }
  ]
}
```

I'm running a plain html file with the images being inserted through a script tag.

I'm getting this error when deploying with now.
```
╶ images/bg01.png        Error               [19s]
╶ images/bg02.png        Building            
╶ images/bg03.png        Error               [19s]
╶ images/bg04.png        Building            
╶ images/bg05.png        Error               [19s]
┌ index.html             Ready               [624ms]
└── index.html
> Error! 3 build failures occured.
```
```
success Cleared cache.
2019-02-27T04:13:38.161Z  Done in 0.86s.
2019-02-27T04:13:38.193Z  [now] cache name undefined
2019-02-27T04:13:38.195Z  [now] workPath is /tmp/700cc82
2019-02-27T04:13:38.195Z  [now] running builder.exports.build...
2019-02-27T04:13:38.209Z  Error: The optipng process exited with a non-zero exit code: 1
                              at OptiPng.onBinComplete (/tmp/utils/build-module/node_modules/optipng/lib/OptiPng.js:93:28)
                              at Object.onceWrapper (events.js:317:30)
                              at emitTwo (events.js:126:13)
                              at ChildProcess.emit (events.js:214:7)
                              at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
2019-02-27T04:13:38.209Z  [now] patching https://api-sfo1.zeit.co/v2/now/deployments/dpl_Ghsx5FywU5EVovt3Ggssem5yJD9A/builds/bld_gssh1xsbl with {"readyState":"ERROR","errorCode":"BUILD_FAILED_2"}
2019-02-27T04:13:38.314Z  Error: The optipng process exited with a non-zero exit code: 1
                              at OptiPng.onBinComplete (/tmp/utils/build-module/node_modules/optipng/lib/OptiPng.js:93:28)
                              at Object.onceWrapper (events.js:317:30)
                              at emitTwo (events.js:126:13)
                              at ChildProcess.emit (events.js:214:7)
                              at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
2019-02-27T04:13:38.315Z  [now] patching https://api-sfo1.zeit.co/v2/now/deployments/dpl_Ghsx5FywU5EVovt3Ggssem5yJD9A/builds/bld_7obfcdi23 with {"readyState":"ERROR","errorCode":"BUILD_FAILED_2"}
```

thanks for any help

**Comment by juliangruber** [comment] 2019-03-07 20:04
@mingsterism can you please share a repository for reproducing this?

**Comment by TooTallNate** [comment] 2019-08-13 02:05
Closing because the `@now/optipng` builder has been deprecated and will no longer be maintained. Please simply use `@now/static` from now on.

**Closed as completed by TooTallNate** 2019-08-13 02:05 UTC
