### ISSUE TITLE
(node:50607) ExperimentalWarning: The http2 module is an experimental API.

### ISSUE THREAD

**Issue by jjhesk** [vercel/vercel#2730] opened 2019-08-08 15:40 UTC
node version is v9.11.0
now version is 16.1.1

please help

use cmd:
`now .`
then i only got the above warning line and no more actions..

maybe it is related to #2676

**Comment by leo** [comment] 2019-08-09 10:40
@jjhesk Which Node.js version are you using?

**Comment by TooTallNate** [comment] 2019-08-09 19:07
When you say "no more actions" you mean that it doesn't deploy?

The warning is removed if you use Node.js version 10.x or newer.

**Comment by leo** [comment] 2019-08-09 19:35
@TooTallNate We need to adjust `engines` to force at least a version that removes this warning. Otherwise it will continue to be reported.

**Comment by jjhesk** [comment] 2019-08-10 07:12
wait.. still not working..

**Comment by jjhesk** [comment] 2019-08-10 07:21
oh wait. i need to install `nvm use 10` then activate node 10.16.2 
`npm remove -g now`
then
reinstall the latest version, login and redo the whole again.

**Comment by leo** [comment] 2019-08-10 11:56
@jjhesk When using `nvm`, you will have several different `npm` module directories (global). This is due to the design of `nvm`.

In turn, you might have to install our package again, once you started using a new Node.js version.

**Comment by barbalex** [comment] 2019-08-11 10:54
I get the same warning when trying to run `now`. Then nothing happens. So no deployment possible any more :-(

node v9.11.2
now v16.1.1
ubuntu on Windows 10

What am I doing wrong?

**Comment by barbalex** [comment] 2019-08-11 11:00
Seems that nodv v9 is not supported any more? I updated to v12.8.0 and it now works :-)

**Comment by leo** [comment] 2019-08-11 12:58
Node.js 9 should still be working. @TooTallNate

**Comment by brandontle** [comment] 2019-08-12 17:27
I'm getting the same error and non-responsive terminal when trying to deploy. I've tried using Node versions:
- v9.10.0
- v10.16.2
- v12.8.0

but no luck. I've also uninstalled and reinstalled global `now` for each of them and I still get stuck at: 
```
(node:5449) ExperimentalWarning: The http2 module is an experimental API.
```

Any tops or progress from anyone? I just migrated from Next 8 to Next 9.0.3.

**Comment by TooTallNate** [comment] 2019-08-12 18:42
I can reproduce the "hanging" behavior with Node 9.

@leo Let's have node < 10 use the regular `http` module instead of `http2`.

**Comment by leo** [comment] 2019-08-13 16:37
@rdev will be adding [now-client](https://github.com/zeit/now-client) to Now CLI. Since it doesn't use HTTP/2 support (which is broken in most Node.js versions anyways), this will give us support for the same Node.js versions that `yarn` supports:

> Node: ^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0

**Comment by jjhesk** [comment] 2019-08-13 16:49
I managed to resolve it by using the nvm and reinstall npm and node.

**Comment by leo** [comment] 2019-08-13 17:07
That's great to hear @jjhesk. But no worries: In future versions of Now CLI, we'll support more Node.js versions **without** any of those warnings.

**Comment by brandontle** [comment] 2019-08-14 18:46
After a full-system restart, `now` no longer hangs at `(node:5449) ExperimentalWarning: The http2 module is an experimental API.` warning with Node v10+, but it does still fail to deploy:

```
Module not found: Can't resolve 'memcpy' in '/tmp/3d7679fe/node_modules/bytebuffer/dist'
Build error occurred
Error: package.json does not exist at /package.json
```

Likely due to Firebase as documented in this issue, so I'll move over there: https://github.com/zeit/next.js/issues/6073

**Comment by jjhesk** [comment] 2019-08-15 09:09
@leo hi, the problem happen again.. it is very annoying.

```
xx webgl xxx$ node -v
v9.11.1

```

```
(node:88192) ExperimentalWarning: The http2 module is an experimental API.
```

**Comment by leo** [comment] 2019-08-15 09:10
@jjhesk I agree!

Currently, you can fix it by upgrading Node.js to [the latest version](https://nodejs.org/en/).

In the near future, we'll release updates for Now CLI that introduce support for even more Node.js versions.

**Comment by jjhesk** [comment] 2019-08-15 09:13
@leo i cannot do the latest version at this time because the system is using it. Can you tell me which version or higher to support it?

**Comment by leo** [comment] 2019-08-18 11:45
@jjhesk 12.8.1 or 10.16.3 should work!

**Comment by leo** [comment] 2019-08-30 09:55
@dmi3y Unfortunately, there's no workaround for old Node.js versions. Node.js is printing this warning because HTTP/2 is not stable on that old Node.js version. The only way to prevent this is by passing a option to `node`, which we can't do here.

If you cannot upgrade your local Node.js, I recommend installing Now CLI 15.8.5 – the last version that ships with its own Node.js binary.

**Comment by styfle** [comment] 2020-03-25 15:53
Closing since we no longer support Node 8.

New deployments will use Node 12 by default since [16.7.0](https://github.com/zeit/now/releases/tag/now%4016.7.0) and Now CLI engines has been updated to 10 or newer #3670.

**Closed as completed by styfle** 2020-03-25 15:53 UTC
Labels: triaged: bug
