### ISSUE TITLE
Python3.7 Support

### ISSUE THREAD

**Issue by mwildehahn** [vercel/vercel#3116] opened 2019-10-02 20:33 UTC
Are there plans to support python3.7? It looks like AWS supports this runtime: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by styfle** [comment] 2019-10-03 12:26
We have an existing issue tracked for this feature request.

Closing as a duplicate of #2979

**Closed as completed by styfle** 2019-10-03 12:26 UTC
