### ISSUE TITLE
Certain node modules in expressjs project cause now to error 

### ISSUE THREAD

**Issue by joshma91** [vercel/vercel#1716] opened 2018-12-02 08:01 UTC
I'm getting the following error when I run `now` on my expressjs project with certain dependencies. 
```
> Synced 2 files (16.28KB) [1s]
> https://nodejs-express-rdxgc6c3s.now.sh [v2] [in clipboard] [1s]
╶ index.js        Error               [14s]
> Error! 1 build failure occured.
> Error! Check your logs at https://nodejs-express-rdxgc6c3s.now.sh/_logs or run `now logs nodejs-express-rdxgc6c3s.now.sh`.
```
The log file in the link will be empty. 

Now works fine when I run `now` on the example here: https://github.com/zeit/now-examples/tree/master/nodejs-express. However, when I run `yarn add ethereumjs-abi` in the same example project and then run `now`, I'll get the error above.

This problem isn't present on now v1, so I've resorted to using that for now.

**Comment by monojack** [comment] 2018-12-02 15:01
Could you post the logs?

**Comment by adrianmcli** [comment] 2018-12-02 17:42
So you're not even using `ethereumjs-abi` at all? You're just adding it to the `dependencies` list with `yarn add` and all of a sudden it fails to build?

Maybe `ethereumjs-abi` can only be built in a specific environment? This is a difficult issue to solve without knowing what exactly went wrong during the `npm install` or `yarn` process on the server.

**Comment by joshma91** [comment] 2018-12-02 17:43
@adrianmcli yes that's correct. Thanks for clarifying

**Comment by davidlares** [comment] 2018-12-02 19:37
Hello.

I'm facing the same problem but with `pug`. As a matter of fact, in my case there's no log available if is synced with a github account on the `now.json`. In previous instances there was a clear message that said `Cannot find module 'pug'`, but the project on the local environment is running well and had a native integration with ExpressJS.

The package is on the dependencies list without any problems. I'll probably reverse this integration to see if is a common package problem or only the referred ones.

If there's something we can do, let us know. I'm happy to help.

Regards.

DL.

**Comment by w01fgang** [comment] 2019-01-12 16:08
I've deployed express example with `pug` and I have the same issue.
I listed files in the directory at the head of the app:
```javascript
fs.readdir(__dirname, (err, files) => {
  console.log('files:', files);
});
```
and here is the output
```javascript
files: [ 'index.js' ]
```

That's because the application was minified with `ncc` to the one single file and there is no `node_modules` and there is no `views` folder with templates.
I don't know how to copy assets, otherwise it's impossible to use `express` with templates like `pug`.

---
### Update: the previous issue seems fixed in the last version.
But still can't make it work.

I add this to the node-express example
```javascript
app.set('view engine', 'pug');
app.set('views', './views');
app.engine('.pug', require('pug').__express); // without this line will be an error "Cannot find module 'pug'"
```
But the next error appears: "Error: Cannot find module '../lib/utils.js'" which is actually the error from uglify-js which is dependency of `pug` => `pug-filters`.

I made a build with `ncc build index.js --external uglify-js` and when I run it there is no error.

Unfortunately, I can't figure out how to specify externals in `now.json`.
Please, @leo or @rauchg can you provide some examples for adding externals to `now.json`?

**Comment by juliangruber** [comment] 2019-03-05 14:38
@joshma91 I can't reproduce the error with `ethereumjs-abi`, can you see if this is fixed in the latest version?

@w01fgang You're right that currently Pug doesn't work with NCC because UglifyJS doesn't work with Webpack (https://github.com/zeit/ncc/issues/254). The `@now/node` builder at this point doesn't support the `--external` option in NCC, but you could open an issue there to expedite the feature's development.

For the time being your best bet with now 2.0 is probably to switch to a more compatible templating engine.

**Comment by TooTallNate** [comment] 2019-08-10 00:49
Closing due to age and inactivity. If you are still experiencing any issues with the `@now/node` builder please create an issue at https://github.com/zeit/now-builders.

**Closed as completed by TooTallNate** 2019-08-10 00:49 UTC
