### ISSUE TITLE
Routes work differently using now dev

### ISSUE THREAD

**Issue by ezakto** [vercel/vercel#3018] opened 2019-09-14 06:16 UTC
I have these routes in my now.json:
```json
  "routes": [
    { "src": "/(page1|page2|page3)(/.*)?", "dest": "/public/index.html" },
    { "src": "/([^/]+[.][a-z]{1,4})", "dest": "/public/$1" },
    ...
  ]
```

The first one works with `now dev` but responds with 404 when deployed.
However, if I change it to:

```json
  "routes": [
    { "src": "/(page1|page2|page3)(/.*)?", "dest": "/" },
    { "src": "/([^/]+[.][a-z]{1,4})", "dest": "/public/$1" },
    ...
  ]
```

This one works when deployed, but responds with the root directory listing using `now dev`.
And, to make it even more strange, the second route works both in dev and deployed :|

**Comment by styfle** [comment] 2019-09-18 19:12
Hi @ezakto 

Thanks for reporting this issue.

Can you provide more information? Specifically, what is your project file structure and what URL are you visiting to get the 404?

If your project is open source, that would be helpful or create a small project to reproduce.

**Comment by kaYcee** [comment] 2019-09-23 09:39
Environment: `MacOS 10.14.6, now CLI 16.2.0, next 9.0.6`

Got a similar issue with basic next.js deployment. My `now.json` looks like this:

```
{
  "version": 2,
  "routes": [
    { "handle": "filesystem" },
    { "src": "/(.*)", "dest": "/" }
  ]
}
```

When deployed, everything works as expected. All my pages in the `\pages` directory are rendered correctly, and any unmatched paths, i.e. `/abc`, `/abc/def/gah` etc. are redirected to the `index` page. 

But this does not work with `now dev`. Instead, I get multiple `Uncaught SyntaxError: Unexpected token '<'` error messages in the console, pages cannot be accessed and static content not rendered anymore.

My current workaround is to remove the routes entries entirely for development and add them back right before deployment.

**Comment by trek** [comment] 2024-08-26 13:41
Hi @ezakto,

Thank you for the bug report. We're closing out older issues that have probably been addressed by now.

**Closed as completed by trek** 2024-08-26 13:41 UTC
Labels: triaged: bug, area: dev
