### ISSUE TITLE
[now dev] Not updating code from import

### ISSUE THREAD

**Issue by g45t345rt** [vercel/vercel#2370] opened 2019-05-21 15:24 UTC
Modifying the code from an import file does not reflect over. 
I need to rebuild with 'now dev' every time for the code to take effect.

e.g:
```
// Lambda serverless function
import { isTest } from '../lib/test' // changing code inside test.js will not take effect

// changing the code from here will update automatically with now ncc
export default (req, res) => {
  if (isTest()) return res.send('This is a test')
  res.send('This is a test')
}
```

**Comment by karl-run** [comment] 2019-05-21 20:26
I'm experiencing the same issue. Issue #2283.

**Comment by netspencer** [comment] 2019-05-26 00:55
same here!

**Comment by TooTallNate** [comment] 2019-05-31 21:27
Closing since this is a duplicate of #2283.

**Closed as completed by TooTallNate** 2019-05-31 21:27 UTC
