### ISSUE TITLE
[now dev] NextJS: not passing query parameters or correct URL 

### ISSUE THREAD

**Issue by cryptiklemur** [vercel/vercel#2234] opened 2019-04-26 02:23 UTC
going to https://mysite.com/browse/foobar

I should expect the following:

```typescript
export default class Page extends React.PureCOmponent {
    public static getInitialProps({query, req}) {
        query.category === 'foobar';

        req.url === '/browse/foobar';
    }
}
```

However, `query` is `{}` and `req.url` is `/browse`

**Comment by fredrik-sogaard** [comment] 2019-05-03 06:41
Is this a duplicate of #2289 ?

**Comment by TooTallNate** [comment] 2019-05-14 22:49
Fixed in https://github.com/zeit/now-cli/pull/2330.

**Closed as completed by TooTallNate** 2019-05-14 22:49 UTC
