### ISSUE TITLE
Handle Docker build returning an error code

### ISSUE THREAD

**Issue by wolverian** [vercel/vercel#88] opened 2016-10-21 11:09 UTC
## Description

Instead of continuing after `docker build` returns a non-zero exit code, now should stop the deployment.
## What happens

An example run of what happens now:

```
scifi» now --version
𝚫 now 0.26.0
scifi» now -e DB_URL=@db-url                                                                          
> Deploying ~/Developer/go/src/kisu.club/scifi
> Using Node.js 6.9.0 (default)
> Ready! https://scifi-bnurmgeuyl.now.sh (copied to clipboard) [4s]
> Initializing…
> Building
> ▲ docker build
>  ---> Using cache
>  ---> ab51cc788ac7
> Step 5 : COPY . /go/src/scifi
>  ---> Using cache
>  ---> 86c222a09002
> Step 6 : RUN go get -d -v
>  ---> Running in be379d337348
> github.com/lib/pq (download)
> go: missing Git command. See https://golang.org/s/gogetcmd
> package github.com/lib/pq: exec: "git": executable file not found in $PATH
> The command 'go get -d -v' returned a non-zero code: 1
> ▲ Storing image
> ▲ docker build
>  ---> f4ef3b6138f0
> Removing intermediate container c3c6d114dc4e
> Step 5 : COPY . /go/src/scifi
>  ---> cd9d38cf7b74
> Removing intermediate container cde385575838
> Step 6 : RUN go get -d -v
>  ---> Running in a71ef90cb15c
> github.com/lib/pq (download)
> go: missing Git command. See https://golang.org/s/gogetcmd
> package github.com/lib/pq: exec: "git": executable file not found in $PATH
> The command 'go get -d -v' returned a non-zero code: 1
> ▲ Storing image
[the build got stuck here I think]
```

It looks like the build falls back to rebuilding the image from scratch if the initial `docker build` fails. If the second build fails too, the deployment seems to hang forever.

(The error in this build is that the image doesn't have `git`, but this report probably applies to any Docker build that returns a non-zero exit code.)
## Expected behaviour

After `docker build` fails, Now should report the error to the user and stop the deployment.

**Comment by vnglst** [comment] 2016-11-11 16:03
I had the same experience, in my case I think the image is too large. Build got stuck on storing image.

> Deploying ~/src/github.com/vnglst/latex-letter
> Two manifests found. Press [n] to deploy or re-run with --flag
> [1] package.json     --npm
> [2] Dockerfile    --docker
> No `name` LABEL in `Dockerfile`, using latex-letter
> Using Node.js 7.0.0 (default)
> Ready! https://latex-letter-epixtubbyl.now.sh (copied to clipboard) [3s]
> Upload [====================] 100% 0.0s
> Sync complete (100.66kB) [4s]
> Initializing…
> Building
> ▲ docker build
> a3ed95caeb02: Pull complete
> a3ed95caeb02: Pull complete
> 1f292910d9d0: Pull complete
> 1f292910d9d0: Pull complete
> 81ba8b68a8bf: Pull complete
> 81ba8b68a8bf: Pull complete
> 9f0bc5a8df30: Pull complete
> 9f0bc5a8df30: Pull complete
> 4760d20f7c78: Pull complete
> 4760d20f7c78: Pull complete
> ▲ Storing image
> ▲ docker build
> 8cfe10adae3e: Verifying Checksum
> 8cfe10adae3e: Download complete
> 5617d7222e70: Verifying Checksum
> 5617d7222e70: Download complete
> add3d79abc5c: Verifying Checksum
> add3d79abc5c: Download complete
> 9b11b62c8f1d: Verifying Checksum
> 9b11b62c8f1d: Download complete
> f49bd4d91305: Verifying Checksum
> f49bd4d91305: Download complete
> ▲ docker build
> a3ed95caeb02: Pull complete
> a3ed95caeb02: Pull complete
> 1f292910d9d0: Pull complete
> 1f292910d9d0: Pull complete
> 9f0bc5a8df30: Pull complete
> 9f0bc5a8df30: Pull complete
> 81ba8b68a8bf: Pull complete
> 81ba8b68a8bf: Pull complete
> 4760d20f7c78: Pull complete
> 4760d20f7c78: Pull complete
> ▲ Storing image
> ▲ docker build
> Removing intermediate container 3663ba9ad5ae
> Step 6 : EXPOSE 3000
>  ---> Running in 6af3360079bf
>  ---> 4e64cf3f052b
> Removing intermediate container 6af3360079bf
> Step 7 : CMD yarn start
>  ---> Running in 5171e07ddd9a
>  ---> 19f36b4884b2
> Removing intermediate container 5171e07ddd9a
> Successfully built 19f36b4884b2
> ▲ Storing image
> ▲ docker build
> a3ed95caeb02: Pull complete
> a3ed95caeb02: Pull complete
> 1f292910d9d0: Pull complete
> 1f292910d9d0: Pull complete
> 9f0bc5a8df30: Pull complete
> 9f0bc5a8df30: Pull complete
> 81ba8b68a8bf: Pull complete
> 81ba8b68a8bf: Pull complete
> 4760d20f7c78: Pull complete
> 4760d20f7c78: Pull complete
> ▲ Storing image
> ▲ docker build
> Removing intermediate container 3663ba9ad5ae
> Step 6 : EXPOSE 3000
>  ---> Running in 6af3360079bf
>  ---> 4e64cf3f052b
> Removing intermediate container 6af3360079bf
> Step 7 : CMD yarn start
>  ---> Running in 5171e07ddd9a
>  ---> 19f36b4884b2
> Removing intermediate container 5171e07ddd9a
> Successfully built 19f36b4884b2
> ▲ Storing image

**Comment by joelburget** [comment] 2016-12-05 19:35
I'm also getting stuck on "▲ Storing image", on both the php example from the introductory blogpost and slackin.

* https://rauchg-slackin-kmqqgsuylz.now.sh/
* https://my-docker-deployment-qozatimefk.now.sh/

**Comment by ctchen** [comment] 2016-12-07 10:57
same here stuck on Storing image, I am using now 0.34.1.

https://now-ebcqaxdtli.now.sh/

**Comment by jamo** [comment] 2016-12-07 11:36
We recently fixed an issue where some docker builds got stuck in "storing image".

The latex letter instead fails since it's just huge (over 6G) 😊  

And we retry builds, regardless how they fail, for a few times, to workaround possible networking issues with builds.

**Comment by joelburget** [comment] 2016-12-07 15:57
The issue is fixed for me, thanks :)

**Comment by jamo** [comment] 2017-01-02 19:07
I'll close this now.
The real issue behind this was fixed when I last updated it; and we retry builds a few times in case the issue is caused by intermittent network issues etc. sure it's kinda stupid for pure syntactical errors...

**Closed as completed by jamo** 2017-01-02 19:07 UTC
