### ISSUE TITLE
Excluding devDependencies from deployment

### ISSUE THREAD

**Issue by tima101** [vercel/vercel#686] opened 2017-06-17 18:10 UTC
I am following instructions in this post: https://zeit.co/docs/features/configuration#files

Running `now -e NODE_ENV="production"` does exclude devDependencies.

To keep deploying with just `now`. I added below configuration to my package.json file:
```
"env": {
  "NODE_ENV": "production"
}
```
When I run `now` - I get **all** dependencies installed, including devDependencies.

Am I missing a step?

I use `next beta` and `yarn v0.21.3`

Thanks

**Comment by epicallan** [comment] 2017-07-26 13:51
same issue

**Comment by albertosantini** [comment] 2018-06-14 17:46
Tested with 

```
$ now -v
11.2.4
```
Adding

```
"env": {
  "NODE_ENV": "production"
}
```
it works correctly.

Did you confirm it?

**Comment by Jolg42** [comment] 2018-07-24 17:22
I have a private package in devDependencies and Now is still trying to install it!

I think you're using yarn?

Here are the logs for `now -e NODE_ENV="production"` (I also tried all other methods...!)

```
> Building…
> ▲ npm install
> npm ERR! Error while executing:
> npm ERR! /usr/bin/git ls-remote -h -t ssh://git@bitbucket.org/user/package.js.git
> npm ERR! 
> npm ERR! fatal: cannot run ssh: No such file or directory
> npm ERR! fatal: unable to fork
> npm ERR! 
> npm ERR! exited with error code: 128
```

As this private is in devDependencies and maked as `"dev": true` in my package-lock.json I just don't understand what's happening.

**Comment by HamadaFMahdi** [comment] 2018-08-03 18:55
In cases where you need to set the NODE_ENV variable to "production", but still need to have the devDependencies installed, then you can use the environment variable on the build script property as shown below:

"scripts": {
  "build": "NODE_ENV=production next build"
}

This is from the docs: https://zeit.co/docs/deployment-types/node

**Comment by leo** [comment] 2018-11-13 12:21
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2

**Comment by TooTallNate** [comment] 2019-08-09 21:27
Closing because I tested just now and can not reproduce this. Dev dependencies are not installed with `now -e NODE_ENV=production`.

**Closed as completed by TooTallNate** 2019-08-09 21:27 UTC
