### ISSUE TITLE
@now/python bundling node_modules

### ISSUE THREAD

**Issue by hipstersmoothie** [vercel/vercel#3603] opened 2020-01-16 08:33 UTC
So I'm trying to get the @now/python builder to work in the same repo as my next.js project. Everytime I have tried to run `now` I get the following error (or something similar):

```
Error: The lambda function size (92.12mb) exceeds the maximum size limit (50mb). Learn more: https://zeit.co/docs/v2/deployments/concepts/lambdas/#maximum-bundle-size
```

This is odd since I just copy-pasted the python example from the docs (I even deleted the cowsay stuff!). first I removed everything to make sure it worked in isolation, it did. After adding things back it seems like the node_modules gets bundled somehow with the python code. 

# Reproduction repo

In this repo you can see my app with everything except the node_module dependencies in the `package.json`. If you run `now` you will get the error. Remove dependencies, run `now`, see bundle size for python function go down.

https://github.com/hipstersmoothie/now-pythno-bug

---

Is there something I'm doing wrong with my repo setup? Or is this an error in the python builder?

**Comment by styfle** [comment] 2020-01-16 14:33
Hi @hipstersmoothie 

Thanks for the repro steps!

We are aware of this issue and planning to add something like `excludeFiles` as a workaround until we can add static analysis to `@now/python` like we have with `@now/node` and `@now/go` functions.

Closing as a duplicate of #2830.

**Closed as completed** 2020-01-16 14:34 UTC
