### ISSUE TITLE
Now dev Error: Unknown file type: undefined

### ISSUE THREAD

**Issue by koficypher** [vercel/vercel#3298] opened 2019-11-12 16:26 UTC
Node - 10.15.3
Npm - 6.13.0
Now version - 16.4.4
i have a svelte mono repo with @now/node functions in my api folder in the project directory. Below is my now.json file.

```js
   {
    "version": 2,
    "builds": [
        {"src": "api/*.js", "use": "@now/node"},
        {"src": "package.json", "use": "@now/static-build"}
    ],
    "routes" : [
        {"src": "api/","dest":"api/controllers/index.js"},
        {"src": "api/positions","dest":"api/positions.js"},
        {"src": "api/candidates","dest":"api/candidates.js"}
    ]
}
```

 Everything was working fine, i only installed jquery which i later remove from the project. After which running `now dev` gives me this error:  
```bash
src/main.js → public/bundle.js...
created public/bundle.js in 3.2s
> Built @now/static-build:package.json [7s]
> Building @now/node:api/positions.js
Installing dependencies...
Error: Unknown file type: undefined
    at Object.<anonymous> (C:\Users\kofi\AppData\Roaming\npm\node_modules\now\dist\index.js:2:3132743)      
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\kofi\AppData\Roaming\npm\node_modules\now\dist\index.js:2:3129512)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by nhuesmann** [comment] 2019-11-12 16:43
I just now experienced this issue as well, and I did not change my code over the weekend. I'm going to see if I can find anything about changes to Now made within the last few days.

**Comment by koficypher** [comment] 2019-11-12 16:45
Felt really weird. I thought i broke something by adding jquery. @nhuesmann  will do same.

**Comment by nhuesmann** [comment] 2019-11-12 16:53
https://twitter.com/zeithq/status/1194282718932226049?s=20. Looks like they are deprecating `builds` in favor of `functions`, but that shouldn't have broken current functionality.

**Comment by koficypher** [comment] 2019-11-12 16:53
Solved:
Updating to now 16.5.0 solved it for me. A new version was  published 2 hours ago 
here: [link](https://github.com/zeit/now/releases/tag/now%4016.5.0)

**Comment by nhuesmann** [comment] 2019-11-12 16:58
@koficypher I'd actually recommend leaving this issue open—they introduced a breaking change into the current version of `now-cli`, which forced us to update to `16.5.0`. This is definitely still an issue.

**Comment by koficypher** [comment] 2019-11-12 16:59
@nhuesmann sounds like a smart thing to do. Leaving it open then

**Comment by HandersonMarinho** [comment] 2019-11-13 00:43
Faced the same issue and was foced to update now-cli :/

**Comment by bitfede** [comment] 2019-11-18 20:14
Had the same `Unknown file type: undefined` error, then I updated now-cli and everything went back to normal working conditions.

**Comment by tunnckoCore** [comment] 2019-11-24 23:29
I can confirm that updating fixes the things. I'm on `now@16.6`.

**Comment by tsujp** [comment] 2019-11-29 06:22
I had this with a previously working project using the Now API, ran `npm update -g now` to `now@16.6` and it works again.

**Comment by ChrisBAshton** [comment] 2019-12-20 20:03
I had the same issue, fixed by upgrading. Beware if you've installed it locally to your project, I had to run `npm upgrade` rather than just `npm update -g now`.

**Comment by styfle** [comment] 2021-03-04 22:28
Newer versions of Vercel CLI ship with `@vercel/node` so you won't get mismatches like this anymore when using [zero config](https://vercel.com/blog/zero-config).

**Closed as completed by styfle** 2021-03-04 22:28 UTC
Labels: area: cli, area: dev
