### ISSUE TITLE
Rm UX varies

### ISSUE THREAD

**Issue by OlliV** [vercel/vercel#681] opened 2017-06-16 09:56 UTC
The rm confirmation varies between commands.

```
% now alias rm xyz.xstack.io
> > The following alias will be removed permanently
  BYYoCpciD9l9xGa8DGR6eSE2      https://pizzatilaus-lgbhlhfniy.now.sh      https://xyz.xstack.io      10s ago
Are you sure? [y|N]
```

`Are you sure?` isn't formatted and continues immediately when I press `Y`.

```
% now certs rm xyzzz.xstack.io
> The following certificate will be removed permanently
  1ahc8kd6p3xmSsby7xLH      xyzzz.xstack.io      1m ago
> Are you sure? [y/N] y
```

Here `Are you sure?` is in red and doesn't continue until I press return.

**Comment by TooTallNate** [comment] 2019-08-16 21:03
Duplicate of https://github.com/zeit/now-cli/issues/14.

**Closed as completed by TooTallNate** 2019-08-16 21:03 UTC
Labels: triaged: bug
