### ISSUE TITLE
Route `/some/:var/https://google.com` gets auto-rewritten

### ISSUE THREAD

**Issue by pke** [vercel/vercel#3429] opened 2019-12-14 01:41 UTC
My nodejs app is able to locally handle this route with a router spec like `/some/var/*`.

However when deployed to now such URL is always 308 (301 in dev) redirected and the `https://google.com` part mangled to `https:/google.com` (missing one slash)

This also happens when running locally with `now dev`

```bash
$ curl http://localhost:3000/mlr/cut/url/https://api.myjson.com/bins/gtcpc
Redirecting to /mlr/cut/url/https:/api.myjson.com/bins/gtcpc (301)
```

Thats my now.json

```json
{
  "version": 2,
  "builds": [
    { "src": "src/mlr.js", "use": "@now/node" }
  ],
  "rewrites": [
    { "source": "/mlr/(.*)", "destination": "src/mlr.js"}
  ]
}
```

**Comment by styfle** [comment] 2019-12-14 13:30
Hi @pke 

A path that contains two or more forward slashes in a row will be redirected to one forward slash.

If you need to preserve a complete URL in a path, you can use JS to encode it first like this:

```js
const api = 'https://api.myjson.com/bins/gtcpc';
const cut = 'http://localhost:3000/mlr/cut/url/' + encodeURIComponent(api);
console.log(cut);
```

We have an issue tracking this feature request to disable double slash redirects in #3086.

Closing as a duplicate of #3086

**Closed as completed by styfle** 2019-12-14 13:30 UTC

**Comment by pke** [comment] 2019-12-14 17:08
Thanks for the swift reply.
I know about URI encoding but the whole reason I did not put the URL as a query param was that I don't want users to burden with encoding it. They should simply be able to write the request URL.

**Comment by xieyuheng** [comment] 2023-02-23 06:51
A poll about adding this feature: https://github.com/vercel/vercel/discussions/9522
