### ISSUE TITLE
Could't find a deployment to alias. Please specify one from the command line.

### ISSUE THREAD

**Issue by jineshshah36** [vercel/vercel#1233] opened 2018-04-03 20:25 UTC
When I run:

    now alias acmeco.arthr.sh -r rules.prod.subdomain.json

I get:

    > Error! Could't find a deployment to alias. Please specify one from the command line.

I'm running now 11.0.0. Before the update today, this command worked fine

**Comment by javivelasco** [comment] 2018-04-03 20:37
Duplicate of #1229

**Closed as completed by javivelasco** 2018-04-03 20:37 UTC

**Comment by jineshshah36** [comment] 2018-04-03 20:49
Is it a duplicate? I'm trying to use path aliases, not a specific deployment.

**Comment by jineshshah36** [comment] 2018-04-04 17:37
Please reopen this issue, it's not fixed
