### ISSUE TITLE
`now dev` on Windows 10 throws "statCache does not contain value for next.config.js"

### ISSUE THREAD

**Issue by joshleblanc** [vercel/vercel#2316] opened 2019-05-04 10:24 UTC
```
C:\Users\horiz\Documents\dev\aa2gd>now dev
> UPDATE AVAILABLE The latest version of Now CLI is 15.1.0
> Read more about how to update here: https://zeit.co/update-cli
> Changelog: https://github.com/zeit/now-cli/releases/tag/15.1.0
> Error! statCache does not contain value for server/index.js (resolved to C:\Users\horiz\Documents\dev\aa2gd\server\index.js)
```

now.json

```
{
    "name": "aa2gd",
    "version": 2,
    "builds": [
      {
        "src": "server/index.js",
        "use": "@now/node-server"
      },
      {
        "src": "client/next.config.js",
        "use": "@now/next"
      }
    ],
    "routes": [
      {
        "src": "/graphql",
        "dest": "server/index.js"
      },
      {
        "src": "/(.*)",
        "dest": "client/$1"
      }
    ],
    "env": {
        "MONGO_URL": "@aa2gd-mongo-url",
        "JWT_SECRET": "@aa2gd-jwt-secret",
        "ENGINE_API_KEY": "@aa2gd-engine-api-key",
        "DISCORD_CLIENT_ID": "@aa2gd-discord-client-id",
        "DISCORD_CLIENT_SECRET": "@aa2gd-discord-client-secret",
        "DISCORD_REDIRECT_URL": "@aa2gd-discord-redirect-url",
        "STEAM_KEY": "@famtime-steam-key"
    },
    "build": {
      "env": {
        "DISCORD_CLIENT_ID": "@aa2gd-discord-client-id",
        "DISCORD_REDIRECT_URL": "@aa2gd-discord-redirect-url",
        "FONTAWESOME_TOKEN": "@fontawesome-token"
      }
    }
  }
```

Someone mentioned in another ticket this should have been fixed by 5.0.11, however I'm still facing it.

**Comment by varbrad** [comment] 2019-05-05 17:38
I am also experiencing the same error on Windows, with a slightly different build setup (I am using `@now/static-build` to create a Svelte application with Rollup).

Repo: https://github.com/varbrad/now-express-svelte-app

**Comment by Erik-Sovereign** [comment] 2019-05-09 10:00
I'm facing the same issue with Windows 10. I use now 15.1.1-canary.3 as suggested in this issue #2145 . 
I'm not sure which files to post. But you can tell me and I will post them.
I'm using now with NextJS.
A repo to reproduce my error is: https://github.com/hanford/next-offline/tree/master/examples/now2

**Comment by TooTallNate** [comment] 2019-08-13 01:42
Closing because this now works as expected. Please create a new issue if you are still experiencing any troubles.

**Closed as completed by TooTallNate** 2019-08-13 01:42 UTC
