### ISSUE TITLE
Node serverless with typescript custom path import errors on now dev

### ISSUE THREAD

**Issue by ch4rlesyeo** [vercel/vercel#3141] opened 2019-10-09 22:06 UTC
Hi,

I'm trying out Now v2 with Node and TypeScript and got an error below when i tried to import from a custom path which I've specified in my tsconfig : 
![image](https://user-images.githubusercontent.com/8202917/66523256-08c42b00-eb22-11e9-9206-099e0230864e.png)

Strangely when i import an interface from another custom path it works.

tsconfig :
![image](https://user-images.githubusercontent.com/8202917/66523391-71aba300-eb22-11e9-9cdc-fbca590bfb72.png)

Perhaps is there a way to use `tsconfig-paths/register` in Now v2 with builders like @zeit/ncc or @now/node?

I'm confused on how Now v2 works for Node serverless structure with TypeScript, was using monolithic tsc and ts-node stack with tsconfig-paths registration previously.

Reproduction repo :
https://github.com/ch4rlesyeo/now-node-server-typescript

Reproduction step :
- run `now dev`
- browse `http://localhost:3000/api`

Note that `http://localhost:3000/api/user` works fine as its not using custom path.

Thanks in advance.

**Comment by paulogdm** [comment] 2019-10-10 16:58
@ch4rlesyeo posted this on Spectrum as well: https://spectrum.chat/zeit/now/node-serverless-with-typescript-custom-path-import-on-now-dev~4b5fa38a-3016-456c-9fc9-0420e01db0cc

**Comment by styfle** [comment] 2019-10-15 22:04
The `paths` key is not implemented yet. See issue #2832

**Comment by styfle** [comment] 2019-10-21 20:10
Closing as a duplicate of #2832

**Closed as completed by styfle** 2019-10-21 20:10 UTC
