### ISSUE TITLE
"This site can’t be reached" after deployment

### ISSUE THREAD

**Issue by abnerlee** [vercel/vercel#1878] opened 2019-02-06 02:52 UTC
After deployment successfully, the website still cannot be opened, it says in Chrome:

```
This site can’t be reached 
The webpage at https://***.now.sh/ might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE
```

We errors on the log, the log end with

```
[now] requisite for "static/blueprint.css" not found. probably, already exists. not uploading
02/06 10:35 AM (15m)
[now] patching https://api-sfo1.zeit.co/v2/now/deployments/dpl_FRq8djHxM9Sy7pWffP14kpwtC6wj/builds/bld_l24jglegr with {"readyState":"DEPLOYING"}
02/06 10:35 AM (15m)
[now] finished
02/06 10:39 AM (11m)
[now] uploading cache (30259 kb) to 70882c3f08f3366185f3b97355affa76e76f8ab5409091d6e3068ed4fe9f21b8...
02/06 10:39 AM (11m)
[now] finished
02/06 10:40 AM (11m)
[now] uploading cache (30258 kb) to b9b62fa8cffb89cc6bfe75239925d264335aeca6ffc6702871da5506c6085c43...
02/06 10:40 AM (11m)
[now] uploading cache (30257 kb) to a8490240f1b8f10265dfc9e40858eb7e212b82361487a968ea823115a7ec0b33...
02/06 10:40 AM (11m)
[now] finished
02/06 10:40 AM (11m)
[now] finished
02/06 10:40 AM (11m)
[now] uploading cache (30258 kb) to 4a3d4b9eab02e3a03f3b1deea61e38f2ece8e423c4c721de70617cf98743a3cf...
02/06 10:40 AM (11m)
[now] uploading cache (30258 kb) to 25e8471cf1bea91757059ade19484259636f32ecdfcad2279f24e8677d5242df...
02/06 10:40 AM (11m)
[now] finished
02/06 10:40 AM (11m)
[now] finished
```

We met https://github.com/zeit/next.js/issues/5750 before this deployment, but this time, no error in our log

**Comment by paulogdm** [comment] 2019-02-06 11:50
Do you see the request in the logs?

**Comment by daikw** [comment] 2019-02-06 15:43
same here and there is no http request in the logs.

<details>
<summary>logs after the access to ***now.sh</summary>
<pre>
<code>
02/06 10:56 PM (2h)
ImageID sha256:940367219e5ee08303cb90029c22d19b286d76fe5e681ccdb7d5e9a4420b7399
02/06 10:56 PM (2h)
[now] sandbox worker for deployment dpl_BWJSeNtpoKYQGuwYnzEAisKDyrw4 build bld_kv1g8adky
02/06 10:56 PM (2h)
[now] patching https://api-sfo1.zeit.co/v2/now/deployments/dpl_BWJSeNtpoKYQGuwYnzEAisKDyrw4/builds/bld_kv1g8adky with {"readyState":"BUILDING","buildLambda":{"logGroupName":"/ecs/build-fargate-task","logStreamName":"ecs/build-fargate-container/16a92bce-907d-4a58-ae82-6c3d301f4810","startedAt":1549461397206}}
02/06 10:56 PM (2h)
[now] cleaning up...
02/06 10:56 PM (2h)
running yarn cache clean...
02/06 10:56 PM (2h)
yarn cache v1.12.3
02/06 10:56 PM (2h)
warning package.json: No license field
02/06 10:56 PM (2h)
success Cleared cache.
02/06 10:56 PM (2h)
Done in 0.05s.
02/06 10:56 PM (2h)
running yarn for @now/build-utils...
02/06 10:56 PM (2h)
yarn add v1.12.3
02/06 10:56 PM (2h)
warning package.json: No license field
02/06 10:56 PM (2h)
info No lockfile found.
02/06 10:56 PM (2h)
warning No license field
02/06 10:56 PM (2h)
[1/4] Resolving packages...
02/06 10:56 PM (2h)
[2/4] Fetching packages...
02/06 10:56 PM (2h)
[3/4] Linking dependencies...
02/06 10:56 PM (2h)
[4/4] Building fresh packages...
02/06 10:56 PM (2h)
success Saved lockfile.
02/06 10:56 PM (2h)
warning No license field
02/06 10:56 PM (2h)
success Saved 37 new dependencies.
02/06 10:56 PM (2h)
info Direct dependencies
02/06 10:56 PM (2h)
└─ @now/build-utils@0.4.34
02/06 10:56 PM (2h)
info All dependencies
02/06 10:56 PM (2h)
├─ @now/build-utils@0.4.34
02/06 10:56 PM (2h)
├─ async-retry@1.2.3
├─ async-sema@2.1.4
├─ balanced-match@1.0.0
├─ brace-expansion@1.1.11
├─ buffer-crc32@0.2.13
02/06 10:56 PM (2h)
├─ concat-map@0.0.1
├─ core-util-is@1.0.2
├─ double-ended-queue@2.1.0-0
├─ end-of-stream@1.4.1
├─ errno@0.1.7
├─ fast-stream-to-buffer@1.0.0
├─ from2@2.3.0
├─ fs-extra@7.0.0
├─ fs.realpath@1.0.0
├─ glob@7.1.3
02/06 10:56 PM (2h)
├─ graceful-fs@4.1.15
├─ inflight@1.0.6
├─ inherits@2.0.3
├─ into-stream@4.0.0
├─ isarray@1.0.0
├─ jsonfile@4.0.0
├─ memory-fs@0.4.1
├─ minimatch@3.0.4
├─ multistream@2.1.1
├─ node-fetch@2.2.0
├─ p-is-promise@2.0.0
02/06 10:56 PM (2h)
├─ path-is-absolute@1.0.1
├─ process-nextick-args@2.0.0
├─ prr@1.0.1
├─ readable-stream@2.3.6
├─ retry@0.12.0
├─ safe-buffer@5.1.2
├─ string_decoder@1.1.1
├─ universalify@0.1.2
├─ util-deprecate@1.0.2
└─ yazl@2.4.3
02/06 10:56 PM (2h)
Done in 1.87s.
02/06 10:56 PM (2h)
running yarn cache clean...
02/06 10:56 PM (2h)
yarn cache v1.12.3
</code>
</pre>
</details>

<details>
<summary>package.json</summary>
<pre>
<code>
{
  "name": "rapid-reader",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/daikw/rapid-reader.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/daikw/rapid-reader/issues"
  },
  "homepage": "https://github.com/daikw/rapid-reader#readme",
  "dependencies": {
    "@material-ui/core": "^3.9.1",
    "@material-ui/icons": "^3.0.2",
    "module-alias": "^2.1.0",
    "next": "^7.0.2",
    "next-redux-wrapper": "^3.0.0-alpha.0",
    "prop-types": "^15.6.2",
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-jss": "^8.6.1",
    "react-redux": "^6.0.0",
    "recharts": "^1.4.2",
    "redux": "^4.0.1",
    "styled-jsx": "^3.2.0"
  },
  "devDependencies": {
    "@types/next": "^7.0.7",
    "@types/next-redux-wrapper": "^2.0.2",
    "@types/node": "^10.12.19",
    "@types/react": "^16.7.22",
    "@types/react-redux": "^7.0.1",
    "@zeit/next-typescript": "^1.1.1",
    "babel-plugin-module-resolver": "^3.1.3",
    "fork-ts-checker-webpack-plugin": "^0.5.2",
    "redux-devtools-extension": "^2.13.7",
    "typescript": "^3.2.4"
  },
  "_moduleAliases": {
    "~": "src"
  }
}
</code>
</pre>
</details>

<details>
<summary>next.config.js</summary>
<pre>
<code>
const withTypescript = require('@zeit/next-typescript')
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin')
const path = require('path')

module.exports = withTypescript({
    webpack(config, options) {
        config.resolve.alias = {
            '~': './src'
        }
        if (options.isServer) {
            config.plugins.push(new ForkTsCheckerWebpackPlugin())
        }
        return config
    }
})
</code>
</pre>
</details>

<details>
<summary>now.json</summary>
<pre>
<code>
{
    "version": 2,
    "name": "rapid-reader",
    "builds": [
        { "src": "next.config.js", "use": "@now/next" }
    ]
}
</code>
</pre>
</details>

**Comment by daikw** [comment] 2019-02-07 04:10
It seems that the deployed app doesn't work since I changed `pages/index.js` to `pages/index.tsx`.

I'm trying to find the reproduction procedure. All your comments or advices are welcome!

**Comment by abnerlee** [comment] 2019-02-07 07:55
No, only deployment log

**Comment by paulogdm** [comment] 2019-02-07 10:27
Can you link me to a minimal example so I can take a look?

**Comment by daikw** [comment] 2019-02-07 10:45
I finally applied the following instruction to my app. It works well for me.
https://github.com/zeit/now-builders/blob/master/errors/now-next-no-serverless-pages-built.md

I don't know why but there may be some wrong interactions in the legacy build.

**Comment by daikw** [comment] 2019-02-07 11:01
here is the reproduction.

1. get [the example app from material-ui with nextjs](https://github.com/mui-org/material-ui/tree/next/examples/nextjs)

2. run `npm install @zeit/next-typescript` and use it in `next.config.js` like following.

```js
const withTypescript = require('@zeit/next-typescript')

module.exports = withTypescript({
  webpack(config, options) {
    return config
  }
})
```

3. add the entry point to `package.json`
```js
  "main": "index.js",
  "dependencies": {
    "next": "^7.0.2",
  }
```

4. add `now.json`
```json
{
    "version": 2,
    "name": "xxx",
    "builds": [
        { "src": "package.json", "use": "@now/next" }
    ]
}
```

5. deploy it by `now`

**Comment by abnerlee** [comment] 2019-02-10 07:00
I think this may caused by #1711

But anyway, possible to run smoke test in the build/deploy task?

**Comment by juliangruber** [comment] 2019-03-07 18:42
> But anyway, possible to run smoke test in the build/deploy task?

Can you please open an issue for this in [zeit/now-builders](https://github.com/zeit/now-builders)?

**Comment by juliangruber** [comment] 2019-03-07 19:53
@daikw looks like you figured out the `@now/next` configuration issue thanks to the docs 🙏 , I'm closing this for now

**Closed as completed by juliangruber** 2019-03-07 19:53 UTC

**Comment by frouo** [comment] 2020-10-14 00:12
Having the same issue with nextjs `9.5.5`, typescript `4.0.3` and make SSR using `export const getServerSideProps = async (ctx) => { ... }` in my `page/index.tsx` file.

The site is deployed using vercel.app github plugin. It appears from time to time. When it appears, I hit refresh button and the website loads correctly.

Do you have any idea how to debug that? Thanks you
