### ISSUE TITLE
When creating a new project in now dev, adding a api directory requires restart of now dev

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2610] opened 2019-07-24 12:55 UTC
Currently, you need to restart now dev in order for the api directory to work when you just added it to an already "running" project:

[functions_dont_work_-_Screen_Capture_7-22-19_4.09.14_PM.mp4.zip](https://github.com/zeit/now-cli/files/3426868/functions_dont_work_-_Screen_Capture_7-22-19_4.09.14_PM.mp4.zip)

**Comment by leo** [comment] 2019-07-24 12:56
@AndyBitz said this:

> This already should not happen, and it works fine for me (couldn't reproduce). So this seems to be another edge case

**Comment by AndyBitz** [comment] 2019-08-19 18:54
We've published some improvements to `now dev` since this issue occurred and since I'm still not able to reproduce it I'll close this issue.

Feel free to reopen if someone is still experiencing the same issue.

**Closed as completed by AndyBitz** 2019-08-19 18:54 UTC
Labels: triaged: bug

**Comment by leo** [comment] 2019-08-21 11:26
Works again!
