### ISSUE TITLE
ImportError: libssl.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lqmanh** [vercel/vercel#2495] opened 2019-07-04 17:59 UTC
As the title says, I encountered this bug with `now dev` _(cloud deployments worked fine)_. I used `@now/python` builder with Sanic.

Other informations:
- OS: Manjaro Linux
- DE: KDE Plasma 5.16

**Comment by alvarogomez93** [comment] 2019-08-28 09:28
this is probably caused by the python runtime installed in  /home/<user>/.cache/co.zeit.f
un/runtimes/python being compiled with a different ssl version currently installed in your system. It also fails when using rhel8 since it uses version 1.1.1. Try to verify if your SSL version is correct and if so you can just link it in /usr/lib64/ using ln -s  <path.to.lib> /usr/lib64/libssl.so.10. You will probably also need to do the same with libcrypto.so

**Comment by leo** [comment] 2019-08-30 09:48
Thanks for reporting this. We'll take a look!

**Comment by styfle** [comment] 2019-09-16 15:52
Hi @lqmanh 

This is fixed on the canary channel. Can you confirm this fixes your issue?

Try `npm i -g now@canary` and if you have now.json, use `@now/python@canary`, thanks!

**Comment by lqmanh** [comment] 2019-09-17 16:28
Hi @styfle ,
Thank you for fixing this. I'll test this when I have time.

**Comment by styfle** [comment] 2019-09-30 13:58
We shipped the change to the stable channel.

Please use `npm i -g now@latest` to install the latest stable version, thanks!

**Closed as completed by styfle** 2019-09-30 13:58 UTC
Labels: triaged: bug, area: python, area: dev
