### ISSUE TITLE
Html Webpack Plugin: TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by foxhound87** [vercel/vercel#167] opened 2016-12-09 19:49 UTC
I'm trying to deploy my github repo with the command:

`now foxhound87/mobx-react-form-demo`

at the end of the install process, when the page is being rendered I get:

```
Html Webpack Plugin:
  TypeError: Cannot read property '0' of undefined
  
  - ExternalModuleFactoryPlugin.js:18 ExternalModuleFactoryPlugin.
    [src]/[6b8981c7f0f59e57253f8dd5b1728ea3f444414d]/lib/ExternalModuleFactoryPl    ugin.js:18:38
  
  - NormalModuleFactory.js:159 
    [src]/[2f29e5542c7b2eaf895a8e435bde063c6e9eba0d]/lib/NormalModuleFactory.js:    159:3
  
  - Tapable.js:75 NormalModuleFactory.applyPluginsAsyncWaterfall
    [src]/[83d7d57e3d1ba8fe04c1aff2eddd6e9eb2c9743c]/lib/Tapable.js:75:69
  
  - NormalModuleFactory.js:144 NormalModuleFactory.create
    [src]/[2f29e5542c7b2eaf895a8e435bde063c6e9eba0d]/lib/NormalModuleFactory.js:    144:8
  
  - Compilation.js:356 Compilation.process [as _addModuleChain]
    [src]/[2f29e5542c7b2eaf895a8e435bde063c6e9eba0d]/lib/Compilation.js:356:16
  
  - Compilation.js:424 Compilation.process [as addEntry]
    [src]/[2f29e5542c7b2eaf895a8e435bde063c6e9eba0d]/lib/Compilation.js:424:7
  
  - SingleEntryPlugin.js:22 SingleEntryPlugin.
    [src]/[6b8981c7f0f59e57253f8dd5b1728ea3f444414d]/lib/SingleEntryPlugin.js:22    :15
  
  - Tapable.js:107 Compiler.applyPluginsParallel
    [src]/[83d7d57e3d1ba8fe04c1aff2eddd6e9eb2c9743c]/lib/Tapable.js:107:14
  
  - Compiler.js:394 Compiler.compile
    [src]/[2f29e5542c7b2eaf895a8e435bde063c6e9eba0d]/lib/Compiler.js:394:7
  
  - Compiler.js:203 Compiler.runAsChild
    [src]/[2f29e5542c7b2eaf895a8e435bde063c6e9eba0d]/lib/Compiler.js:203:7
  
  - compiler.js:70 
    [src]/[148c3f08e6d2b8bccadebe51d637be0c7349be5b]/lib/compiler.js:70:19
  
  - debuggability.js:299 Promise._execute
    [src]/[953ea8d4badc1212d26071638946cd40c7f53f6b]/js/release/debuggability.js    :299:9
  
  - promise.js:481 Promise._resolveFromExecutor
    [src]/[953ea8d4badc1212d26071638946cd40c7f53f6b]/js/release/promise.js:481:1    8
  
  - promise.js:77 new Promise
    [src]/[953ea8d4badc1212d26071638946cd40c7f53f6b]/js/release/promise.js:77:14  
  - compiler.js:69 Object.compileTemplate
    [src]/[148c3f08e6d2b8bccadebe51d637be0c7349be5b]/lib/compiler.js:69:10
  
  - index.js:47 Compiler.
    [src]/[148c3f08e6d2b8bccadebe51d637be0c7349be5b]/index.js:47:40
```

**Comment by jamo** [comment] 2016-12-09 19:51
Duplicate of #160 
Current workaround is to downgrade `react-scripts` to version `0.7.0`

**Closed as completed** 2016-12-09 20:59 UTC

**Comment by LukyVj** [comment] 2017-01-18 18:21
@foxhound87 Did the workaround worked for you ?

**Comment by foxhound87** [comment] 2017-01-18 19:05
@LukyVj yes it is

**Comment by shabanraza** [comment] 2017-05-05 08:44
I am getting same error  after upgrading my **package.json**    "react-scripts": "0.9.5",

**Comment by shabanraza** [comment] 2017-05-05 08:48
**After upgrading package.json**

Error in   TypeError: Cannot read property '0' of undefined
  
  - ExternalModuleFactoryPlugin.js:19 
    [fanmojo_react]/[webpack]/lib/ExternalModuleFactoryPlugin.js:19:40
  
  - NormalModuleFactory.js:159 
    [fanmojo_react]/[react-scripts]/[webpack]/lib/NormalModuleFactory.js:159:3
  
  - Tapable.js:75 NormalModuleFactory.applyPluginsAsyncWaterfall
    [fanmojo_react]/[tapable]/lib/Tapable.js:75:69
  
  - NormalModuleFactory.js:144 NormalModuleFactory.create
    [fanmojo_react]/[react-scripts]/[webpack]/lib/NormalModuleFactory.js:144:8
  
  - Compilation.js:356 Compilation.process [as _addModuleChain]
    [fanmojo_react]/[react-scripts]/[webpack]/lib/Compilation.js:356:16
  
  - Compilation.js:424 Compilation.process [as addEntry]
    [fanmojo_react]/[react-scripts]/[webpack]/lib/Compilation.js:424:7
  
  - SingleEntryPlugin.js:24 Compiler.compiler.plugin
    [fanmojo_react]/[webpack]/lib/SingleEntryPlugin.js:24:16
  
  - Tapable.js:107 Compiler.applyPluginsParallel
    [fanmojo_react]/[tapable]/lib/Tapable.js:107:14
  
  - Compiler.js:394 Compiler.compile
    [fanmojo_react]/[react-scripts]/[webpack]/lib/Compiler.js:394:7
  
  - Compiler.js:203 Compiler.runAsChild
    [fanmojo_react]/[react-scripts]/[webpack]/lib/Compiler.js:203:7
  
  - compiler.js:70 
    [fanmojo_react]/[html-webpack-plugin]/lib/compiler.js:70:19
  
  - compiler.js:69 Object.compileTemplate
    [fanmojo_react]/[html-webpack-plugin]/lib/compiler.js:69:10
  
  - index.js:47 Compiler.<anonymous>
    [fanmojo_react]/[html-webpack-plugin]/index.js:47:40
