### ISSUE TITLE
An unexpected error occurred in alias.

### ISSUE THREAD

**Issue by jayfallon** [vercel/vercel#1234] opened 2018-04-03 20:29 UTC
Just trying to alias a new deployment of a static build site and receiving the following error:

```now alias https://out-igihzekeig.now.sh jayfallon.net
> Asigning alias jayfallon.net to deployment out-igihzekeig.now.sh
> Error! An unexpected error occurred in alias: TypeError: Cannot read property 'bru1' of undefined
    at getScaleForDC (/snapshot/repo/dist/now.js:3801:35)
    at shouldCopyScalingAttributes (/snapshot/repo/dist/now.js:3806:10)
    at assignAlias (/snapshot/repo/dist/now.js:4431:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)```

Using Node v8.9.4, now-cli 11.0.0, next v5.1.0.

**Comment by javivelasco** [comment] 2018-04-03 20:36
Duplicate of #1230

**Closed as completed by javivelasco** 2018-04-03 20:36 UTC
