### ISSUE TITLE
now does not identify now.json file in project directory

### ISSUE THREAD

**Issue by guns2410** [vercel/vercel#354] opened 2017-02-25 07:01 UTC
I have `package.json` and `Dockerfile` in the root of the project directory and the type of deployment is mentioned in `now.json` file, however, now does not identify the `now.json` file and asks to choose the type of deployment.

Here is my now.json file

```json
{
  "name": "project-name",
  "type": "docker",
  "alias": "domain-alias-here",
  "env": {
    "NODE_ENV": "production"
  },
  "files": [
    "dist"
  ]
}
```

<img width="586" alt="screen shot 2017-02-25 at 12 32 54 pm" src="https://cloud.githubusercontent.com/assets/1809012/23329095/9482bc06-fb56-11e6-8944-ce4ad249c024.png">

**Comment by leo** [comment] 2017-02-25 08:00
Duplicate of https://github.com/zeit/now-cli/issues/266

**Closed as completed by leo** 2017-02-25 08:00 UTC
