### ISSUE TITLE
Tricky to remove "noname" deployments

### ISSUE THREAD

**Issue by igorklopov** [vercel/vercel#632] opened 2017-06-04 17:34 UTC
now 6.3.1, macos

```
mkdir ___
cd ___
echo hi > index.html
now
now ls
```
New deployment is displayed like `-fnsqorsefa.now.sh`. Without `https://` and starting with dash. When i try to remove it via `now rm -fnsqorsefa.now.sh` it does not work because something starting with a dash is not recognized as deployment name. It works if i prepend `https://`, but it is not easy to guess because i can run `now ls` at any time and i don't have `https://` in the list.

**Comment by nkzawa** [comment] 2017-06-09 15:16
I think this wouldn't be a problem since I remember deploying apps with no name is not allowed now.

**Comment by nkzawa** [comment] 2017-06-09 15:17
Oh, I got the problem is you can still deploy apps with no name 🤔

**Comment by OlliV** [comment] 2018-01-28 18:04
This is now fixed and we compute a hash for the first part of the name if a the original name doesn't result a valid shortened prefix name.

**Closed as completed by OlliV** 2018-01-28 18:04 UTC
