### ISSUE TITLE
[now dev]: async tasks are inconsistent with production

### ISSUE THREAD

**Issue by bitjson** [vercel/vercel#3101] opened 2019-09-30 17:19 UTC
When a lambda ends with an async task, `now dev` completes the task, but the production does not. 

Repo to reproduce: https://github.com/bitjson/now-dev-async-bug

Example: I have a simple endpoint which always returns a response synchronously. After sending the response, I trigger an async task, like logging to another system or calling a Slack webhook. Using `now dev`, these tasks work reliably, but in production, they usually fail.

Is there a reliable way to call an async task after sending a response on the now platform?

**Comment by bitjson** [comment] 2019-09-30 17:27
It seems like the process might be frozen as soon as a response is sent? When the lambda is invoked again, the task may complete:
```
START RequestId: 4b986256-5bdc-44dc-8b74-f4e1bf62304e Version: $LATEST
2019-09-30T17:17:55.012Z	4b986256-5bdc-44dc-8b74-f4e1bf62304e	INFO	Beginning asyncTask...
END RequestId: 4b986256-5bdc-44dc-8b74-f4e1bf62304e
REPORT RequestId: 4b986256-5bdc-44dc-8b74-f4e1bf62304e	Duration: 49.25 ms	Billed Duration: 100 ms	Memory Size: 3008 MB	Max Memory Used: 84 MB	Init Duration: 190.40 ms	
START RequestId: 4cb11a39-13ac-4205-a66d-1e827df19a40 Version: $LATEST
2019-09-30T17:18:03.503Z	4b986256-5bdc-44dc-8b74-f4e1bf62304e	INFO	asyncTask complete
2019-09-30T17:18:03.508Z	4cb11a39-13ac-4205-a66d-1e827df19a40	INFO	Beginning asyncTask...
END RequestId: 4cb11a39-13ac-4205-a66d-1e827df19a40
REPORT RequestId: 4cb11a39-13ac-4205-a66d-1e827df19a40	Duration: 3.32 ms	Billed Duration: 100 ms	Memory Size: 3008 MB	Max Memory Used: 84 MB	
START RequestId: 7eac58d4-a151-47c4-a745-a580da7f00c9 Version: $LATEST
2019-09-30T17:20:15.423Z	4cb11a39-13ac-4205-a66d-1e827df19a40	INFO	asyncTask complete
2019-09-30T17:20:15.427Z	7eac58d4-a151-47c4-a745-a580da7f00c9	INFO	Beginning asyncTask...
END RequestId: 7eac58d4-a151-47c4-a745-a580da7f00c9
REPORT RequestId: 7eac58d4-a151-47c4-a745-a580da7f00c9	Duration: 2.86 ms	Billed Duration: 100 ms	Memory Size: 3008 MB	Max Memory Used: 85 MB	
```

(If the process uses a network connection, it fails silently?)

**Comment by styfle** [comment] 2019-10-01 13:52
Your example code is missing a return statement so the task is not awaited.

**Comment by bitjson** [comment] 2019-10-01 19:18
Right, I know it's possible to modify the code.

I'm concerned that `now dev` deterministically differs from production in this simplified scenario. And other similar scenarios won't be so obviously flawed – they're likely to make it to production and break unexpectedly.

**Comment by paulogdm** [comment] 2020-04-07 00:23
@bitjson Unfortunately, `now dev` can't reproduce this level of behavior since it is tied to the environment itself. I believe the best approach would be to simply educate our userbase about this limitation instead of implementing it in the code of `now dev` making it more complex.

For that reason, we can close this ticket until `now dev` has been revamped.

**Comment by paulogdm** [comment] 2020-04-07 00:23
If you have any further questions, feel free to email support@zeit.co

**Closed as completed by paulogdm** 2020-04-07 00:23 UTC
Labels: triaged: bug, area: dev
