### ISSUE TITLE
Error upon ENOSYS kill

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2673] opened 2019-07-31 16:16 UTC
We've had [this error](https://sentry.io/organizations/zeithq/issues/1115731504/?referrer=slack) for a long while now. We need to fix it.

![image](https://user-images.githubusercontent.com/6170607/62229102-42104a00-b3bf-11e9-8358-d091e8bf2eb3.png)

**Comment by TooTallNate** [comment] 2019-10-17 22:40
Duplicate of #2564.

**Closed as completed by TooTallNate** 2019-10-17 22:40 UTC
Labels: triaged: bug
