### ISSUE TITLE
ENOENT error with now dev on Windows

### ISSUE THREAD

**Issue by woubuc** [vercel/vercel#2318] opened 2019-05-05 07:48 UTC
Running `now dev` results in an error saying `Error: spawn yarn ENOENT`

- Windows 10
- Now v15.1.0
- Yarn v1.15.2
- Node v10.15.0

Now.json:
```json
{
  "version": 2,
  "env": {
    "NODE_ENV": "production"
  },
  "builds": [
    { "src": "package.json", "use": "@now/static-build" }
  ]
}
```

Package.json:
```json
{
  "scripts": {
    "now-build": "parcel build index.html",
    "now-dev": "parcel index.html"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.3"
  },
  "dependencies": {
    "vue": "^2.6.10",
    "vue-router": "^3.0.6"
  }
}
```

Debug output:
```
now dev --debug
> [debug] [2019-05-05T07:45:37.121Z] Found config in file C:\Dev\js\project\now.json
> [debug] [2019-05-05T07:45:37.128Z] Using Now CLI 15.1.0
> [debug] [2019-05-05T07:45:37.131Z] user supplied known subcommand
> Now CLI 15.1.0 dev (beta) — https://zeit.co/feedback/dev
> [debug] [2019-05-05T07:45:37.205Z] The yarn executable is already cached, not re-downloading
> [debug] [2019-05-05T07:45:37.206Z] The nsfw module is already cached, not re-downloading
> [debug] [2019-05-05T07:45:37.207Z] Reading `now.json` file
> [debug] [2019-05-05T07:45:37.212Z] Locating files C:\Dev\js\project
> [debug] [2019-05-05T07:45:37.214Z] Ignoring C:\Dev\js\project\.cache
> [debug] [2019-05-05T07:45:37.215Z] Ignoring C:\Dev\js\project\.gitignore
> [debug] [2019-05-05T07:45:37.216Z] Ignoring C:\Dev\js\project\node_modules
> [debug] [2019-05-05T07:45:37.220Z] Locating files C:\Dev\js\project: 6.522ms
> [debug] [2019-05-05T07:45:46.401Z] Locating files C:\Dev\js\project
> [debug] [2019-05-05T07:45:46.401Z] Locating files C:\Dev\js\project: 0.038ms
> [debug] [2019-05-05T07:45:46.517Z] Adding build match for "package.json"
> Setting up 1 Builder
> Building @now/static-build:package.json
> [debug] [2019-05-05T07:45:46.520Z] v0.5.2 (workPath = C:\Users\Wouter\AppData\Local\Temp\co.zeit.now\dev\workPaths\osf04ph4)
> [debug] [2019-05-05T07:45:46.520Z] Creating build process for package.json
downloading user files...
installing to C:\Users\Wouter\AppData\Local\Temp\co.zeit.now\dev\workPaths\osf04ph4
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
> [debug] [2019-05-05T07:46:09.220Z] Build process for package.json exited with 1
> Error! Builder exited with 1 before sending build result
> [debug] [2019-05-05T07:46:09.222Z] Error: Builder exited with 1 before sending build result
    at ChildProcess.onExit (C:\snapshot\repo\dist\index.js:1:1799670)
    at ChildProcess.emit (events.js:187:15)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)

```

**Comment by peyck** [comment] 2019-05-06 08:50
Same error here, but with Python 3.
"Error! spawn C:\Users\Peter\AppData\Local\Temp\15bb633a\bin\pip ENOENT"

Windows 10
Now v15.1.0

now.json
```
{
    "version": 2,
    "name": "namelist-api-zeit-now",
    "builds": [
        { "src": "*.py", "use": "@now/python", "config": { "maxLambdaSize": "20mb" }},
        { "src": "*.html", "use": "@now/static"},
        { "src": "*.js", "use": "@now/static"}
    ],
    "routes": [
        { "src": "/start", "dest": "/start.html"},
        { "src": "/.*", "dest": "/"}
    ]
}
```

output
```
> [debug] [2019-05-06T08:30:40.327Z] Found config in file E:\dev\proj\now.json
> [debug] [2019-05-06T08:30:40.335Z] Using Now CLI 15.1.0
> [debug] [2019-05-06T08:30:40.339Z] user supplied known subcommand
> Now CLI 15.1.0 dev (beta) — https://zeit.co/feedback/dev
> [debug] [2019-05-06T08:30:40.418Z] The yarn executable is already cached, not re-downloading
> [debug] [2019-05-06T08:30:40.419Z] The nsfw module is already cached, not re-downloading
> [debug] [2019-05-06T08:30:40.420Z] Reading `now.json` file
> [debug] [2019-05-06T08:30:40.426Z] Locating files E:\dev\proj
> [debug] [2019-05-06T08:30:40.443Z] Locating files E:\dev\proj: 16.079ms
> [debug] [2019-05-06T08:30:44.595Z] Locating files E:\dev\proj
> [debug] [2019-05-06T08:30:44.595Z] Locating files E:\dev\proj: 0.053ms
> [debug] [2019-05-06T08:30:44.751Z] Locating files E:\dev\proj
> [debug] [2019-05-06T08:30:44.752Z] Locating files E:\dev\proj: 0.046ms
> [debug] [2019-05-06T08:30:44.754Z] Locating files E:\dev\proj
> [debug] [2019-05-06T08:30:44.755Z] Locating files E:\dev\proj: 0.009ms
> [debug] [2019-05-06T08:30:44.756Z] Adding build match for "index.py"
> [debug] [2019-05-06T08:30:44.756Z] Adding build match for "splits.py"
> [debug] [2019-05-06T08:30:44.756Z] Adding build match for "start.html"
> Setting up 2 Builders
> Building @now/python:index.py
> [debug] [2019-05-06T08:30:44.759Z] v0.1.0 (workPath = C:\Users\Peter\AppData\Local\Temp\co.zeit.now\dev\workPaths\rovq3ec8)
> [debug] [2019-05-06T08:30:44.760Z] Creating build process for index.py
downloading files...
downloading "get-pip.py"...
running "python get-pip.py"...
Collecting pip
  Using cached https://files.pythonhosted.org/packages/f9/fb/863012b13912709c13cf5cfdbfb304fa6c727659d6290438e1a88df9d848/pip-19.1-py2.py3-none-any.whl
Installing collected packages: pip
Successfully installed pip-19.1
running "pip install --target . --upgrade werkzeug"...
Het systeem kan het opgegeven pad niet vinden.
failed to run "pip install --target . --upgrade werkzeug"...
> Error! spawn C:\Users\Peter\AppData\Local\Temp\2ed6fb08\bin\pip ENOENT
> [debug] [2019-05-06T08:30:57.574Z] Error: spawn C:\Users\Peter\AppData\Local\Temp\2ed6fb08\bin\pip ENOENT
    at notFoundError (C:\Users\Peter\AppData\Roaming\co.zeit.now\Caches\dev\builders\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\Peter\AppData\Roaming\co.zeit.now\Caches\dev\builders\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\Peter\AppData\Roaming\co.zeit.now\Caches\dev\builders\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
> [debug] [2019-05-06T08:30:57.579Z] Build process for index.py exited with 1
```

**Comment by TooTallNate** [comment] 2019-05-17 17:58
#2358 should solve this. We'll be releasing a canary shortly so that you can test it out.

**Comment by TooTallNate** [comment] 2019-05-17 20:35
Can you please try now-cli `15.2.1-canary.2` and let me know if that works for you?

**Comment by peyck** [comment] 2019-05-18 11:59
I don't have this error anymore on 15.2.0
There are other problems now, but this one is gone.

**Comment by peyck** [comment] 2019-05-18 12:08
Tried 15.2.1-canary.2
This ENOENT error does not occur anymore.
But compared to 15.2.0 I now get a OSError: [WinError 145]

**Comment by TooTallNate** [comment] 2019-05-28 23:26
@peyck Please create a new issue for the new error 🙏 

Closing this one.

**Comment by leo** [comment] 2019-06-03 21:44
Users are still experiencing this with the latest update.

**Comment by Martialis39** [comment] 2019-06-06 06:22
Still getting the same error after updating to 15.4.0

![image](https://user-images.githubusercontent.com/17801528/59011228-958d6e00-883c-11e9-8f46-0d4990785185.png)

Now.json

`
{
  "version": 2,
  "name": "my-react-app",
  "builds": [
    {
      "src": "package.json",
      "use": "@now/static-build",
      "config": {
        "distDir": "build"
      }
    },
    {
      "src": "api/get/index.js",
      "use": "@now/node"
    },
    {
      "src": "api/postToDb/index.js",
      "use": "@now/node"
    },
    {
      "src": "api/archiveExpense/index.js",
      "use": "@now/node"
    }
  ],
  "routes": [
    {
      "src": "/static/(.*)",
      "headers": {
        "cache-control": "s-maxage=31536000,immutable"
      },
      "dest": "/static/$1"
    },
    {
      "src": "/api/archiveExpense",
      "dest": "api/archiveExpense/index.js"
    },
    {
      "src": "/api/postToDb",
      "dest": "api/postToDb/index.js"
    },
    {
      "src": "/api/get",
      "dest": "api/get/index.js"
    },
    {
      "src": "/favicon.ico",
      "dest": "/favicon.ico"
    },
    {
      "src": "/precache-manifest.(.*)",
      "dest": "/precache-manifest.$1"
    },
    {
      "src": "/service-worker.js",
      "headers": {
        "cache-control": "s-maxage=0"
      },
      "dest": "/service-worker.js"
    },
    {
      "src": "/(.*)",
      "headers": {
        "cache-control": "s-maxage=0"
      },
      "dest": "/index.html"
    }
  ]
}
`

I just tried `now dev` on a fresh create-react-app project, initiated with `now init`, and it produces the same error.

**Comment by marcotorre** [comment] 2019-06-10 15:17
I have a similar issue with a Python dev environment.

Getting this error before and after upgrading to 15.4: "**Error: spawn C:\Users\...\AppData\Local\Temp\***\bin\pipenv_to_requirements ENOENT
    at notFoundError**"

Now: 15.4.0
Python: 3.7.1

`
...
Successfully installed certifi-2019.3.9 chardet-3.0.4 idna-2.8 requests-2.22.0 urllib3-1.25.3
found "Pipfile.lock"
running "pip install --disable-pip-version-check --user  pipenv_to_requirements"...
Collecting pipenv_to_requirements
  Using cached https://files.pythonhosted.org/packages/bc/50/97503a7268649fcd8c07dc9eb377cab73468b01230dbbe97ace24ef93f6c/pipenv_to_requirements-0.7.1-py2.py3-none-any.whl
Requirement already satisfied: pipenv in c:\users\...\appdata\local\programs\python\python37\lib\site-packages (from pipenv_to_requirements) (2018.11.26)
Collecting pbr>=3.0 (from pipenv_to_requirements)
  Using cached https://files.pythonhosted.org/packages/49/a2/e641de6c7e559e0a03a8d3c7b42199158b17a8cf2f96e11e7f725c2e730d/pbr-5.2.1-py2.py3-none-any.whl
Requirement already satisfied: pip>=9.0.1 in c:\users\...\appdata\local\programs\python\python37\lib\site-packages (from pipenv->pipenv_to_requirements) (19.1.1)
Requirement already satisfied: setuptools>=36.2.1 in c:\users\...\appdata\local\programs\python\python37\lib\site-packages (from
pipenv->pipenv_to_requirements) (39.0.1)
Requirement already satisfied: virtualenv-clone>=0.2.5 in c:\users\...\appdata\local\programs\python\python37\lib\site-packages (from pipenv->pipenv_to_requirements) (0.5.3)
Requirement already satisfied: certifi in c:\users\...\appdata\local\programs\python\python37\lib\site-packages (from pipenv->pipenv_to_requirements) (2019.3.9)
Requirement already satisfied: virtualenv in c:\users\...\appdata\local\programs\python\python37\lib\site-packages (from pipenv->pipenv_to_requirements) (16.1.0)
Installing collected packages: pbr, pipenv-to-requirements
  WARNING: The script pbr.exe is installed in 'C:\Users\...\AppData\Local\Temp\***\Python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pipenv_to_requirements.exe is installed in 'C:\Users\...\AppData\Local\Temp\***\Python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pbr-5.2.1 pipenv-to-requirements-0.7.1
running "pipenv_to_requirements -f
The system cannot find the path specified.
failed to run "pipenv_to_requirements -f"
{ Error: spawn C:\Users\...\AppData\Local\Temp\***\bin\pipenv_to_requirements ENOENT
    at notFoundError (C:\Users\...\AppData\Roaming\co.zeit.now\Caches\dev\builders\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\...\AppData\Roaming\co.zeit.now\Caches\dev\builders\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\...\AppData\Roaming\co.zeit.now\Caches\dev\builders\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
  message:
   'spawn C:\\Users\\...\\AppData\\Local\\Temp\\***\\bin\\pipenv_to_requirements ENOENT',
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall:
   'spawn C:\\Users\\...\\AppData\\Local\\Temp\\***\\bin\\pipenv_to_requirements',
  path:
   'C:\\Users\\...\\AppData\\Local\\Temp\\***\\bin\\pipenv_to_requirements',
  spawnargs: [ '-f' ],
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd:
   'C:\\Users\\...\\AppData\\Local\\Temp\\***\\bin\\pipenv_to_requirements -f',
  timedOut: false,
  killed: false }
{ Error: spawn C:\Users\...\AppData\Local\Temp\***\bin\pipenv_to_requirements ENOENT
    at notFoundError (C:\Users\...\AppData\Roaming\co.zeit.now\Caches\dev\builders\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\...\AppData\Roaming\co.zeit.now\Caches\dev\builders\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\...\AppData\Roaming\co.zeit.now\Caches\dev\builders\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
  message:
   'spawn C:\\Users\\...\\AppData\\Local\\Temp\\***\\bin\\pipenv_to_requirements ENOENT',
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall:
   'spawn C:\\Users\\...\\AppData\\Local\\Temp\\***\\bin\\pipenv_to_requirements',
  path:
   'C:\\Users\\...\\AppData\\Local\\Temp\\***\\bin\\pipenv_to_requirements',
  spawnargs: [ '-f' ],
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd:
   'C:\\Users\\...\\AppData\\Local\\Temp\\***\\bin\\pipenv_to_requirements -f',
  timedOut: false,
  killed: false }
`

**Comment by Martialis39** [comment] 2019-06-14 09:47
To add to my previous comment, the issue is now fixed for me.

**Comment by jfl1977** [comment] 2019-06-14 15:48
I am experiencing it too
Windows 10
now 15.5.0
yarn 1.16.0
node 10.16.0

**Comment by marcotorre** [comment] 2019-06-14 18:15
Also updated to now version 15.5.0 and the error still exists.

**Comment by schempil** [comment] 2019-06-21 07:50
Same for me, 15.5.0 an error still appears

**Comment by kidonng** [comment] 2019-07-03 12:15
The bug disappeared after `now@15.6.2` (or some earlier version).
Close the issue?

**Closed as completed** 2019-08-13 01:43 UTC

**Comment by colemars** [comment] 2019-08-19 07:44
Getting this error with next.js app attempting to run `now dev`
