### ISSUE TITLE
Clarify "npm prepare" on the Now platform.

### ISSUE THREAD

**Issue by paulogdm** [vercel/vercel#3632] opened 2020-01-21 14:06 UTC
It seems the platform is not behaving as expected when there is a `"prepare"` script present in dependencies. Reproduction steps can be found below:

## Steps to reproduce

```
git clone https://github.com/derrickreimer/npm-install-should-fail.git
cd npm-install-should-fail
now
```

## Expected behavior

The build should fail.

When you run `npm install` locally, it will fail with an error like this (because we planted a failure in prepare script: https://github.com/derrickreimer/npm-prepare-fail/blob/master/package.json#L7)

```
npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > npm-prepare-fail@1.0.0 prepare /Users/derrickreimer/.npm/_cacache/tmp/git-clone-864ec1db
npm ERR! prepareGitDep > echo "Prepare failed!" && exit 1
npm ERR! prepareGitDep
npm ERR! prepareGitDep Prepare failed!
npm ERR! prepareGitDep
```

## Actual behavior

The build succeeds.

**Comment by styfle** [comment] 2020-01-21 14:13
This is a bug with `yarn install` as seen in https://github.com/yarnpkg/yarn/issues/1671

If you add a `package-lock.json` file, then `npm install` will be used, otherwise `yarn install` will be used.

**Comment by derrickreimer** [comment] 2020-01-21 18:00
Hey @styfle! I will try to repro this with a `package-lock.json` file present. (I initially discovered the behavior in a real-world scenario where there was a lock file present and `prepare` was not getting executed.)

**Comment by derrickreimer** [comment] 2020-01-21 18:36
Here are some new repro steps:

```
git clone https://github.com/derrickreimer/npm-install-prepare-test.git
cd npm-install-prepare-test
now
now logs {deploymentId}
```

The log output looks like this:

```
2020-01-21T18:31:29.317Z  Downloading 4 deployment files...
2020-01-21T18:31:30.153Z  Installing build runtime...
2020-01-21T18:31:30.155Z  yarn info @now/build-utils@latest...
2020-01-21T18:31:30.159Z  yarn info @now/static-build...
2020-01-21T18:31:30.673Z  Build runtime installed: 519.988ms
2020-01-21T18:31:31.114Z  Looking up build cache...
2020-01-21T18:31:31.603Z  Running builder.exports.build...
2020-01-21T18:31:31.606Z  Installing dependencies...
2020-01-21T18:31:32.927Z  npm WARN npm-install-prepare-test@1.0.0 No description
2020-01-21T18:31:32.927Z  npm WARN npm-install-prepare-test@1.0.0 No repository field.
2020-01-21T18:31:32.927Z  
2020-01-21T18:31:32.928Z  added 1 package in 0.978s
2020-01-21T18:31:32.935Z  Running "npm run build"
2020-01-21T18:31:33.120Z  
2020-01-21T18:31:33.120Z  > npm-install-prepare-test@1.0.0 build /zeit/6c02413e
2020-01-21T18:31:33.120Z  > ls -la node_modules/npm-install-prepare-test-dep
2020-01-21T18:31:33.120Z  
2020-01-21T18:31:33.125Z  total 16
2020-01-21T18:31:33.125Z  drwxr-xr-x 2 root root 4096 Jan 21 18:31 .
2020-01-21T18:31:33.125Z  drwxr-xr-x 3 root root 4096 Jan 21 18:31 ..
2020-01-21T18:31:33.125Z  -rw-r--r-- 1 root root   28 Oct 26  1985 index.js
2020-01-21T18:31:33.125Z  -rw-r--r-- 1 root root 1241 Jan 21 18:31 package.json
2020-01-21T18:31:36.205Z  Running builder.exports.prepareCache...
2020-01-21T18:31:36.213Z  Build completed. Populating build cache...
2020-01-21T18:31:36.302Z  Build cache uploaded [573.00 B]: 81.008ms
2020-01-21T18:31:36.306Z  done
```

If the `prepare` script had run for my git dependency, I would expect to see a `build.js` in the list when running `ls -la node_modules/npm-install-prepare-test-dep`. Instead, the build artifact is not present.

**Comment by styfle** [comment] 2020-01-21 20:00
This looks like a bug with npm.

I see the `build.js` file on macOS but I don't see it on Linux.

Here's the steps to reproduce:

```Dockerfile
FROM amazonlinux:2

RUN yum install -y git tar
  && mkdir /node12
  && curl https://nodejs.org/dist/v12.13.1/node-v12.13.1-linux-x64.tar.gz
      | tar -zx --strip-components=1 -C /node12
  && export PATH="/node12/bin:$PATH" 

RUN git clone https://github.com/derrickreimer/npm-install-prepare-test
  && cd npm-install-prepare-test
  && npm install
  && npm run build
```

I found a somewhat related issue here: https://github.com/npm/npm/issues/19684

**Comment by mcsdevv** [comment] 2020-05-13 23:52
Closing as this is an npm issue and not platform-specific.

**Closed as completed by mcsdevv** 2020-05-13 23:52 UTC
Labels: triaged: bug
