### ISSUE TITLE
Cannot alias external domain that is hosted on DNSimple

### ISSUE THREAD

**Issue by saamo** [vercel/vercel#566] opened 2017-05-22 13:24 UTC
When I run `$ now alias myapp-lffhmvgecs.now.sh myapp.example.com`, I get the following error:

```
> myapp.example.com is a custom domain.
> Verifying the DNS settings for myapp.example.com (see https://zeit.world for help)
> Verification OK!
> Provisioning certificate for myapp.example.com
> Error! Unknown error: Error: Invalid challenge response for myapp.example.com. Make sure the DNS records are correct.
Error: Invalid challenge response for myapp.example.com. Make sure the DNS records are correct.
    at console./snapshot/home/travis/build/zeit/now-cli/lib/index.js.module.exports.EventEmitter.createCert.domain.retry (evalmachine.<anonymous>:0:0)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

The domain is hosted via DNSimple.

**Comment by thisjeremiah** [comment] 2017-05-25 22:41
I am getting this same issue for my custom domain that is hosted on Network Solutions.

**Comment by terkelg** [comment] 2017-06-16 12:53
I have the same issue. Also, `now cert create [domain]`returns `Error! Unexpected error. Please try later. (Invalid challenge response for [domain]. Make sure the DNS records are correct.)`

**Comment by OlliV** [comment] 2017-06-16 13:33
Sometimes it may take some time before the DNS records are propagated to Let's Encrypt. Also make sure that you have proper CNAME record for the alias.

**Comment by dblodorn** [comment] 2017-07-10 01:27
@OlliV I'm having this same issue when trying to use now alias - with a domain purchased through name cheap - have tried a number of approaches to no avail. I used the txt record configuration, tried with name cheap, then pointed the domain to cloudflare and tried this: https://zeit.co/blog/domain-verification / also tried the ziet.world nameservers - no luck - I am able to add the domain but cant alias due to the certificate issue, so after a full day - wondering what my options are - as I really wish this would work - because its awesome  (if it works). Can I just alias without ssl?

**Comment by seanpowell** [comment] 2017-07-18 22:42
I'm also having the same issue with Namecheap.  Cannot setup a subdomain.  I get to the exact same point as the original poster.

**Comment by seanpowell** [comment] 2017-07-18 23:19
Heads up that I was able to get another subdomain to work w/ namecheap so I'm thinking it was an issue with how I was attempting to setup the DNS (adding/removing/etc).  In order to setup the subdomain correctly, there are only two records needed: 

1. CNAME record w/ alias
Ex: CNAME | myapp.mydomain.com | alias.zeit.co

2. Txt record with security verification number
Ex. Txt Record  | _now | abs3485739485hsfU...

That worked for me.  Hope this helps.

**Comment by OlliV** [comment] 2017-07-19 20:14
Check the domain shows as verified in `now domain ls`
It's also possible to manually add the domain with `now domain add -e domain.com`, note that you should always register the naked domain with `now` despite you are probably really pointing a subdomain towards now. If you are aliasing the naked domain from an external nameserver, then your nameserver provider should support alias records of some sort, or `CNAME` flattening like Cloudflare is doing.

**Comment by simontegg** [comment] 2017-09-04 09:01
I also couldn't quite get this to work
My domain is on https://iwantmyname.com
I got `dev.my-domain.co` aliasing but `staging.my-domain.co` wouldn't alias.
I made the mistake of removing the domain and starting again and now neither work.
Like @dblodorn I tried external domains and zeit nameservers but no luck

**Comment by simontegg** [comment] 2017-09-04 19:18
I switched over to cloudflare nameservers and followed the docs precisely and it works now.
Possibly related to #188 getting fixed, or maybe I just needed more patience waiting for the dns propagation

**Comment by tima101** [comment] 2017-09-19 21:50
@OlliV My domain was originally on Namecheap nameservers, I switched to Zeit's nameservers and checked whether it has propagated via [ whatsmydns.com](https://www.whatsmydns.net/#NS/builderbook.org). It had propagated.

When I run ```now ln xxx.now.sh my-domain.com```, I get this error:
```
> Verifying the DNS settings for builderbook.org (see https://zeit.world for help)
> Detected zeit.world nameservers! Configuring records.
> DNS Configured! Verifying propagation…
> Error! > We configured the DNS settings for your alias, but we were unable to verify that they've propagated. Please try the alias again later.
```
When I run ```now ln xxx.now.sh my-domain.com``` _again_, I get new error:
```
> Verifying the DNS settings for builderbook.org (see https://zeit.world for help)
> Detected zeit.world nameservers! Configuring records.
> Error! Please make sure that your nameservers point to zeit.world.
> Examples: (full list at https://zeit.world)
> - california.zeit.world    173.255.215.107
> - newark.zeit.world        173.255.231.87
> - london.zeit.world        178.62.47.76
> - singapore.zeit.world     119.81.97.170
> Alternatively, ensure it resolves to alias.zeit.co via CNAME / ALIAS.
```
now version 8.3.5

Any idea why I get the first error after NS change propagated? Thanks.

**Comment by OlliV** [comment] 2017-09-19 22:02
Run
```
now domains ls
now dns ls
```

I suppose everything is ok with the domain but the new DNS records haven't propagated yet.

**Comment by tima101** [comment] 2017-09-19 22:05
@OlliV Thanks for quick reply. I guess so, but NS change has propagated according to: https://www.whatsmydns.net/#NS/builderbook.org

And yes, domain verification is _true_ and dns is _zeit.world_
DNS records are good as well: CNAME/ALIAS  *  alias.zeit.co

**Comment by OlliV** [comment] 2017-09-19 22:14
Yeah, if you see the domain as verified in `now domains ls` then `NS` records are ok from our point of view. The problem is that DNS records are hard to get propagated fast. For example sometimes a local DSL router caches old `A` records for too long etc. Check the records from some other location if possible. I assume you are seeing an `ALIAS` records and a `CNAME` record for you domain with `now dns ls`.

**Comment by tima101** [comment] 2017-09-19 23:01
Thanks, works now, should've been more patient.

**Comment by anonymouce** [comment] 2017-09-28 15:26
Can i host my ghost blog on zeit Now Free using Cloud flare CNAME Flattening.  I was hosting it on Openshift Online v2 which is closing on September 28.

**Comment by OlliV** [comment] 2017-11-10 12:59
Yes you can.

**Closed as completed** 2018-01-07 17:00 UTC
