### ISSUE TITLE
Getting an error when trying to provision a certificate

### ISSUE THREAD

**Issue by Stumblor** [vercel/vercel#976] opened 2017-11-10 09:42 UTC
either via:
```
now certs create shipatron.io
```

or 

```
now alias
```

I get back:

> Error! Unexpected error. Please try again later. (invalid json response body at https://api.zeit.co/now/certs reason: Unexpected token N in JSON at position 0)

I'm using Cloudflare and have followed all the steps outlined [here](https://zeit.co/docs/features/dns#adding-a-domain-using-external-nameservers). Appreciate any help.

**Comment by Qix-** [comment] 2017-11-10 14:48
We're deploying a fix for this right now.

**Comment by Stumblor** [comment] 2017-11-10 15:40
@Qix great, thanks!

**Comment by Stumblor** [comment] 2017-11-10 15:42
Now getting the same message as previously:

> Error! Unknown error: Error: Invalid challenge response for {domain}. Make sure the DNS records are correct.
> Error: Invalid challenge response for {domain}. Make sure the DNS records are correct.
>     at module.exports.EventEmitter.createCert.domain.retry (/snapshot/now-cli/dist/now.js:916:15)
>     at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by Qix-** [comment] 2017-11-10 15:44
@Stumblor How new is the domain?

**Comment by Stumblor** [comment] 2017-11-10 15:45
@Qix Over 2 weeks, but made the switch to CloudFlare yesterday lunchtime.

**Comment by Qix-** [comment] 2017-11-12 06:29
Did that fix the issue then?

**Comment by Stumblor** [comment] 2017-11-13 10:43
@Qix- Sorry, no, still getting the same error ('Invalid challenge response for {domain}. Make sure the DNS records are correct.'). Could this be a problem with how I've setup the DNS?

![image](https://user-images.githubusercontent.com/3416626/32721768-8a36d0da-c85f-11e7-89ff-3a5f6a700872.png)

**Comment by Stumblor** [comment] 2017-11-13 10:45
![image](https://user-images.githubusercontent.com/3416626/32721847-c8d6aae0-c85f-11e7-925d-01bb7fae287c.png)

![image](https://user-images.githubusercontent.com/3416626/32721867-d531a2cc-c85f-11e7-8a47-447a6a21bda7.png)

**Comment by Stumblor** [comment] 2017-11-15 09:28
@OlliV Sorry to harrass but any word on this?

**Comment by atinux** [comment] 2017-11-15 13:46
I have the same problem and since 12 hours my domain is now inaccessible: https://nuxtjs.org/

I got this error:
> Error! Unknown error: Error: Invalid challenge response for nuxtjs.org. Make sure the DNS records are correct.
  Error: Invalid challenge response for nuxtjs.org. Make sure the DNS records are correct.
    at module.exports.EventEmitter.createCert.domain.retry (/snapshot/now-cli/dist/now.js:924:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by OlliV** [comment] 2017-11-15 21:42
A workaround for now is to set the DNS records to DNS-only mode, renew the certs manually with `now certs renew <domain>`, and re-enable the cache mode in Cloudflare. I'm not yet sure about the root cause because renewing works with my test domains.

One thing to keep in mind is also the new requirement for `CAA` records even though this doesn't seem to be affecting you right now:
https://community.letsencrypt.org/t/legacy-caa-implementation/42335

**Comment by Stumblor** [comment] 2017-11-20 20:51
@OlliV Where do you set DNS only mode? Tried in fiddling with both the security settings and caching but no luck so far.

**Comment by OlliV** [comment] 2017-11-20 21:57
![image](https://user-images.githubusercontent.com/1401625/33043556-2b28cfe8-ce46-11e7-8d9c-1a645ff621ab.png)

**Comment by OlliV** [comment] 2017-11-20 21:58
![image](https://user-images.githubusercontent.com/1401625/33043604-4a289c34-ce46-11e7-8ea0-651ebefdc1b5.png)
and did you also set this?

**Comment by Stumblor** [comment] 2017-11-20 22:10
@OlliV Brilliant thanks dude that DNS only setting fixed it. Thanks for your help!

**Closed as completed** 2018-05-27 20:45 UTC
