### ISSUE TITLE
`vercel dev` crashes when serving images with next/image

### ISSUE THREAD

**Issue by DavidChouinard** [vercel/vercel#6243] opened 2021-05-15 16:44 UTC
When using using an image loaded with [next/image](https://nextjs.org/docs/api-reference/next/image), `vercel dev` throws an error in the console: `Failed to complete request to /_next/image?url={...}: Error: socket hang up` Subsequent refreshes of the page lead to 404 errors and the only way to restore expected behavior is to ^C and restart `vercel dev`

- This only happens on pages that use next/image (not regular images)
- This only happens locally with `vercel dev`, deploys to Vercel work as expected

<img width="501" alt="Screen Shot 2021-05-14 at 11 18 41 AM" src="https://user-images.githubusercontent.com/388552/118371257-9ec30180-b560-11eb-8a05-28aee9b82c6e.png">

### Environment

macOS Big Sur
Vercel 22.0.1
Node.js 16.2.0
Next.js 10.2.0

### Steps to reproduce

- Locate the official next/image demo in the `examples/image-component` directory of the Next.js project ([here](https://github.com/vercel/next.js/tree/canary/examples/image-component))
- Run `npm install`
- Run `vercel dev`
- Open http://localhost:3000/layout-fixed in a browser, observe `vercel dev` crash

### Previous attempts at resolving the issue

Reinstalled `node_modules`, reinstalled Node, reinstalled Mac OS command line utilities.

**Comment by DavidChouinard** [comment] 2021-05-23 05:06
Downgrading to Node v14 resolve the issue, this appears to be the same issue as https://github.com/vercel/next.js/issues/24564

**Comment by timneutkens** [comment] 2021-05-24 09:39
Closing as duplicate of https://github.com/vercel/next.js/issues/24421 given it's a Next.js issue and not specific to `vercel dev` where it just runs Next.js.

**Closed as completed by timneutkens** 2021-05-24 09:39 UTC
