### ISSUE TITLE
now-cli remove does not work

### ISSUE THREAD

**Issue by Ailrun** [vercel/vercel#1638] opened 2018-11-08 22:21 UTC
## Description
I cannot delete legacy deployments that is created with now-cli@11.
I tried to delete them using now-cli and using web dashboard, and neither of them work.
## Informations
One of legacy deployments I tried to delete is `angelswing-354-qvfiqzttjk.now.sh`.
## Note
`now rm [deployment name]` said `Success! 1 deployment removed [1m]` after 1 minute, but the deployment is still there.

**Comment by robertgrzonka** [comment] 2018-11-08 23:31
How did you try to delete it? What commands do you use? Did you seen any errors?

Please try this: `now rm angelswing-354-qvfiqzttjk.now.sh`

**Comment by Ailrun** [comment] 2018-11-08 23:43
@robertgrzonka
1. As I said, it gives me `Success` message after 1 minute, and actual deployment is not deleted.
2. And web dashboard gives me UNKNOWN_ERROR response with 200 status code (in the network tab of development tool)

**Comment by robertgrzonka** [comment] 2018-11-08 23:56
Okay, sorry, I have this Issue opened and wrote answer without reloading page.

That's weird because I've tried it on one of my deployments and it works. Try `now logs angelswing-354-qvfiqzttjk` and please show what it print. 

Other option which is coming to my mind: please try to delete it with `Now Desktop` and then `now logs angelswing-354-qvfiqzttjk`.

**Comment by Ailrun** [comment] 2018-11-09 00:10
@robertgrzonka `now logs` said `> Error! Failed to find deployment "angelswing-354-qvfiqzttjk" in [my-team]` where **I can access deployed site and I also can see that it is listed on the dashboard**.

**Comment by Ailrun** [comment] 2018-11-09 00:11
And I'm on Manjaro so I cannot use desktop app. (and I don't believe it works since even web dashboard does not work with UNKNOWN_ERROR response from server)

**Comment by Ailrun** [comment] 2018-11-13 08:05
When I tried to delete them in web dashboard, it displayed me an error like following
> Error when deleting deployments

where network requests were still going on.
After few minute, it did remove those deployments. However, when I tried to remove deployments in CLI, it took more than a minute and did not display anything, and gave me
> \> Error! Not found (404)

**Comment by leo** [comment] 2018-11-13 13:35
The team is working on a fix for this!

**Comment by santosguilherme** [comment] 2019-05-07 20:15
I deleted a project with `now project rm <project-name>`, but the project's deployments are still accessible on `now ls` and still deployed.

Is that the expected behavior?

**Comment by santosguilherme** [comment] 2019-05-08 18:01
As a workaround, I run `now rm <project-name>` which remove all deployments started with the project name.

**Comment by jscottsf** [comment] 2019-06-17 22:37
Similar problem.

```
now ls xyz-web-site

> Fetched 13 deployments under abc [232ms]
> To list deployment instances run `now ls --all [project]`

  project                     latest deployment                            inst #    type    state    age
  xyz-web-site    xyz-web-site-p4y1c54zs.now.sh         -    -       READY    11m
  xyz-web-site    xyz-web-site-hh0gog39q.now.sh         -    -       READY    5h
  xyz-web-site    xyz-web-site-9uffab28t.now.sh         -    -       READY    4d
...
  xyz-web-site    xyz-web-site-fd4s07osy.now.sh         -    -       READY    55d

: xyz-web-site user$ now rm xyz-web-site-fd4s07osy.now.sh
> Could not find any deployments matching "xyz-web-site-fd4s07osy.now.sh". Run `now ls` to list.
```

Tried many variations. I usually have to log into the web portal to manage.

**Comment by Samleo8** [comment] 2019-07-06 15:34
> As a workaround, I run `now rm <project-name>` which remove all deployments started with the project name.

Unfortunately this workaround doesn't work for me. After deleting the project and creating a new project of the same name (cos it's linked to my Github), it just shows me the old deployments again. Doesn't work on Now web dashboard either.

Also, I affirmed that I can delete deployments for **Now v2.0 but not legacy v1.0**

**Comment by TooTallNate** [comment] 2019-08-12 20:55
Closing because I just tried deleting an individual v1 deployment as well as a project that contained v1 deployments, and both were deleted as expected. I recall that there was an issue at the API level when this issue was created, and that issue has now been fixed.

Please create a new issue if you are still experiencing any issues.

**Closed as completed by TooTallNate** 2019-08-12 20:55 UTC
Labels: triaged: bug
